const starTrekEnterprise = [
    { season: 1, episode: 1, name: "Broken Bow, Part I" },
    { season: 1, episode: 2, name: "Broken Bow, Part II" },
    { season: 1, episode: 3, name: "Fight or Flight" },
    { season: 1, episode: 4, name: "Strange New World" },
    { season: 1, episode: 5, name: "Unexpected" },
    { season: 1, episode: 6, name: "Terra Nova" },
    { season: 1, episode: 7, name: "The Andorian Incident" },
    { season: 1, episode: 8, name: "Breaking the Ice" },
    { season: 1, episode: 9, name: "Civilization" },
    { season: 1, episode: 10, name: "Fortunate Son" },
    { season: 1, episode: 11, name: "Cold Front" },
    { season: 1, episode: 12, name: "Silent Enemy" },
    { season: 1, episode: 13, name: "Dear Doctor" },
    { season: 1, episode: 14, name: "Sleeping Dogs" },
    { season: 1, episode: 15, name: "Shadows of P'Jem" },
    { season: 1, episode: 16, name: "Shuttlepod One" },
    { season: 1, episode: 17, name: "Fusion" },
    { season: 1, episode: 18, name: "Rogue Planet" },
    { season: 1, episode: 19, name: "Acquisition" },
    { season: 1, episode: 20, name: "Oasis" },
    { season: 1, episode: 21, name: "Detained" },
    { season: 1, episode: 22, name: "Vox Sola" },
    { season: 1, episode: 23, name: "Fallen Hero" },
    { season: 1, episode: 24, name: "Desert Crossing" },
    { season: 1, episode: 25, name: "Two Days and Two Nights" },
    { season: 1, episode: 26, name: "Shockwave, Part I" },
    { season: 2, episode: 1, name: "Shockwave, Part II" },
    { season: 2, episode: 2, name: "Carbon Creek" },
    { season: 2, episode: 3, name: "Minefield" },
    { season: 2, episode: 4, name: "Dead Stop" },
    { season: 2, episode: 5, name: "A Night in Sickbay" },
    { season: 2, episode: 6, name: "Marauders" },
    { season: 2, episode: 7, name: "The Seventh" },
    { season: 2, episode: 8, name: "The Communicator" },
    { season: 2, episode: 9, name: "Singularity" },
    { season: 2, episode: 10, name: "Vanishing Point" },
    { season: 2, episode: 11, name: "Precious Cargo" },
    { season: 2, episode: 12, name: "The Catwalk" },
    { season: 2, episode: 13, name: "Dawn" },
    { season: 2, episode: 14, name: "Stigma" },
    { season: 2, episode: 15, name: "Cease Fire" },
    { season: 2, episode: 16, name: "Future Tense" },
    { season: 2, episode: 17, name: "Canamar" },
    { season: 2, episode: 18, name: "The Crossing" },
    { season: 2, episode: 19, name: "Judgment" },
    { season: 2, episode: 20, name: "Horizon" },
    { season: 2, episode: 21, name: "The Breach" },
    { season: 2, episode: 22, name: "Cogenitor" },
    { season: 2, episode: 23, name: "Regeneration" },
    { season: 2, episode: 24, name: "First Flight" },
    { season: 2, episode: 25, name: "Bounty" },
    { season: 2, episode: 26, name: "The Expanse" },
    { season: 3, episode: 1, name: "The Xindi" },
    { season: 3, episode: 2, name: "Anomaly" },
    { season: 3, episode: 3, name: "Extinction" },
    { season: 3, episode: 4, name: "Rajiin" },
    { season: 3, episode: 5, name: "Impulse" },
    { season: 3, episode: 6, name: "Exile" },
    { season: 3, episode: 7, name: "The Shipment" },
    { season: 3, episode: 8, name: "Twilight" },
    { season: 3, episode: 9, name: "North Star" },
    { season: 3, episode: 10, name: "Similitude" },
    { season: 3, episode: 11, name: "Carpenter Street" },
    { season: 3, episode: 12, name: "Chosen Realm" },
    { season: 3, episode: 13, name: "Proving Ground" },
    { season: 3, episode: 14, name: "Stratagem" },
    { season: 3, episode: 15, name: "Harbinger" },
    { season: 3, episode: 16, name: "Doctor's Orders" },
    { season: 3, episode: 17, name: "Hatchery" },
    { season: 3, episode: 18, name: "Azati Prime" },
    { season: 3, episode: 19, name: "Damage" },
    { season: 3, episode: 20, name: "The Forgotten" },
    { season: 3, episode: 21, name: "E²" },
    { season: 3, episode: 22, name: "The Council" },
    { season: 3, episode: 23, name: "Countdown" },
    { season: 3, episode: 24, name: "Zero Hour" },
    { season: 4, episode: 1, name: "Storm Front, Part I" },
    { season: 4, episode: 2, name: "Storm Front, Part II" },
    { season: 4, episode: 3, name: "Home" },
    { season: 4, episode: 4, name: "Borderland" },
    { season: 4, episode: 5, name: "Cold Station 12" },
    { season: 4, episode: 6, name: "The Augments" },
    { season: 4, episode: 7, name: "The Forge" },
    { season: 4, episode: 8, name: "Awakening" },
    { season: 4, episode: 9, name: "Kir'Shara" },
    { season: 4, episode: 10, name: "Daedalus" },
    { season: 4, episode: 11, name: "Observer Effect" },
    { season: 4, episode: 12, name: "Babel One" },
    { season: 4, episode: 13, name: "United" },
    { season: 4, episode: 14, name: "The Aenar" },
    { season: 4, episode: 15, name: "Affliction" },
    { season: 4, episode: 16, name: "Divergence" },
    { season: 4, episode: 17, name: "Bound" },
    { season: 4, episode: 18, name: "In a Mirror, Darkly, Part I" },
    { season: 4, episode: 19, name: "In a Mirror, Darkly, Part II" },
    { season: 4, episode: 20, name: "Demons" },
    { season: 4, episode: 21, name: "Terra Prime" },
    { season: 4, episode: 22, name: "These Are the Voyages..." }
    ];

    const tosEpisodes = [
        { season: 1, episode: 1, name: "The Man Trap" },
        { season: 1, episode: 2, name: "Charlie X" },
        { season: 1, episode: 3, name: "Where No Man Has Gone Before" },
        { season: 1, episode: 4, name: "The Naked Time" },
        { season: 1, episode: 5, name: "The Enemy Within" },
        { season: 1, episode: 6, name: "Mudd's Women" },
        { season: 1, episode: 7, name: "What Are Little Girls Made Of?" },
        { season: 1, episode: 8, name: "Miri" },
        { season: 1, episode: 9, name: "Dagger of the Mind" },
        { season: 1, episode: 10, name: "The Corbomite Maneuver" },
        { season: 1, episode: 11, name: "The Menagerie, Part I" },
        { season: 1, episode: 12, name: "The Menagerie, Part II" },
        { season: 1, episode: 13, name: "The Conscience of the King" },
        { season: 1, episode: 14, name: "Balance of Terror" },
        { season: 1, episode: 15, name: "Shore Leave" },
        { season: 1, episode: 16, name: "The Galileo Seven" },
        { season: 1, episode: 17, name: "The Squire of Gothos" },
        { season: 1, episode: 18, name: "Arena" },
        { season: 1, episode: 19, name: "Tomorrow Is Yesterday" },
        { season: 1, episode: 20, name: "Court Martial" },
        { season: 1, episode: 21, name: "The Return of the Archons" },
        { season: 1, episode: 22, name: "Space Seed" },
        { season: 1, episode: 23, name: "A Taste of Armageddon" },
        { season: 1, episode: 24, name: "This Side of Paradise" },
        { season: 1, episode: 25, name: "The Devil in the Dark" },
        { season: 1, episode: 26, name: "Errand of Mercy" },
        { season: 2, episode: 1, name: "Amok Time" },
        { season: 2, episode: 2, name: "Who Mourns for Adonais?" },
        { season: 2, episode: 3, name: "The Changeling" },
        { season: 2, episode: 4, name: "Mirror, Mirror" },
        { season: 2, episode: 5, name: "The Apple" },
        { season: 2, episode: 6, name: "The Doomsday Machine" },
        { season: 2, episode: 7, name: "Catspaw" },
        { season: 2, episode: 8, name: "I, Mudd" },
        { season: 2, episode: 9, name: "Metamorphosis" },
        { season: 2, episode: 10, name: "Journey to Babel" },
        { season: 2, episode: 11, name: "Friday's Child" },
        { season: 2, episode: 12, name: "The Deadly Years" },
        { season: 2, episode: 13, name: "Obsession" },
        { season: 2, episode: 14, name: "Wolf in the Fold" },
        { season: 2, episode: 15, name: "The Trouble with Tribbles" },
        { season: 2, episode: 16, name: "The Gamesters of Triskelion" },
        { season: 2, episode: 17, name: "A Piece of the Action" },
        { season: 2, episode: 18, name: "The Immunity Syndrome" },
        { season: 2, episode: 19, name: "A Private Little War" },
        { season: 2, episode: 20, name: "Return to Tomorrow" },
        { season: 2, episode: 21, name: "Patterns of Force" },
        { season: 2, episode: 22, name: "By Any Other Name" },
        { season: 2, episode: 23, name: "The Omega Glory" },
        { season: 2, episode: 24, name: "The Ultimate Computer" },
        { season: 2, episode: 25, name: "Bread and Circuses" },
        { season: 2, episode: 26, name: "Assignment: Earth" },
        { season: 3, episode: 1, name: "Spock's Brain" },
        { season: 3, episode: 2, name: "The Enterprise Incident" },
        { season: 3, episode: 4, name: "And the Children Shall Lead" },
        { season: 3, episode: 5, name: "Is There in Truth No Beauty?" },
        { season: 3, episode: 6, name: "Spectre of the Gun" },
        { season: 3, episode: 7, name: "Day of the Dove" },
        { season: 3, episode: 9, name: "The Tholian Web" },
        { season: 3, episode: 10, name: "Plato's Stepchildren" },
        { season: 3, episode: 11, name: "Wink of an Eye" },
        { season: 3, episode: 12, name: "The Empath" },
        { season: 3, episode: 13, name: "Elaan of Troyius" },
        { season: 3, episode: 14, name: "Whom Gods Destroy" },
        { season: 3, episode: 15, name: "Let That Be Your Last Battlefield" },
        { season: 3, episode: 16, name: "The Mark of Gideon" },
        { season: 3, episode: 17, name: "That Which Survives" },
        { season: 3, episode: 18, name: "The Lights of Zetar" },
        { season: 3, episode: 19, name: "Requiem for Methuselah" },
        { season: 3, episode: 20, name: "The Way to Eden" },
        { season: 3, episode: 21, name: "The Cloud Minders" },
        { season: 3, episode: 22, name: "The Savage Curtain" },
        { season: 3, episode: 23, name: "All Our Yesterdays" },
        { season: 3, episode: 24, name: "Turnabout Intruder" }
        ];