const entEpisodes = [
    {show:"Star Trek: Enterprise", season: 1, episode: 1, name: "Broken Bow, Part I" },
    {show:"Star Trek: Enterprise", season: 1, episode: 2, name: "Broken Bow, Part II" },
    {show:"Star Trek: Enterprise", season: 1, episode: 3, name: "Fight or Flight" },
    {show:"Star Trek: Enterprise", season: 1, episode: 4, name: "Strange New World" },
    {show:"Star Trek: Enterprise", season: 1, episode: 5, name: "Unexpected" },
    {show:"Star Trek: Enterprise", season: 1, episode: 6, name: "Terra Nova" },
    {show:"Star Trek: Enterprise", season: 1, episode: 7, name: "The Andorian Incident" },
    {show:"Star Trek: Enterprise", season: 1, episode: 8, name: "Breaking the Ice" },
    {show:"Star Trek: Enterprise", season: 1, episode: 9, name: "Civilization" },
    {show:"Star Trek: Enterprise", season: 1, episode: 10, name: "Fortunate Son" },
    {show:"Star Trek: Enterprise", season: 1, episode: 11, name: "Cold Front" },
    {show:"Star Trek: Enterprise", season: 1, episode: 12, name: "Silent Enemy" },
    {show:"Star Trek: Enterprise", season: 1, episode: 13, name: "Dear Doctor" },
    {show:"Star Trek: Enterprise", season: 1, episode: 14, name: "Sleeping Dogs" },
    {show:"Star Trek: Enterprise", season: 1, episode: 15, name: "Shadows of P'Jem" },
    {show:"Star Trek: Enterprise", season: 1, episode: 16, name: "Shuttlepod One" },
    {show:"Star Trek: Enterprise", season: 1, episode: 17, name: "Fusion" },
    {show:"Star Trek: Enterprise", season: 1, episode: 18, name: "Rogue Planet" },
    {show:"Star Trek: Enterprise", season: 1, episode: 19, name: "Acquisition" },
    {show:"Star Trek: Enterprise", season: 1, episode: 20, name: "Oasis" },
    {show:"Star Trek: Enterprise", season: 1, episode: 21, name: "Detained" },
    {show:"Star Trek: Enterprise", season: 1, episode: 22, name: "Vox Sola" },
    {show:"Star Trek: Enterprise", season: 1, episode: 23, name: "Fallen Hero" },
    {show:"Star Trek: Enterprise", season: 1, episode: 24, name: "Desert Crossing" },
    {show:"Star Trek: Enterprise", season: 1, episode: 25, name: "Two Days and Two Nights" },
    {show:"Star Trek: Enterprise", season: 1, episode: 26, name: "Shockwave, Part I" },
    {show:"Star Trek: Enterprise", season: 2, episode: 1, name: "Shockwave, Part II" },
    {show:"Star Trek: Enterprise", season: 2, episode: 2, name: "Carbon Creek" },
    {show:"Star Trek: Enterprise", season: 2, episode: 3, name: "Minefield" },
    {show:"Star Trek: Enterprise", season: 2, episode: 4, name: "Dead Stop" },
    {show:"Star Trek: Enterprise", season: 2, episode: 5, name: "A Night in Sickbay" },
    {show:"Star Trek: Enterprise", season: 2, episode: 6, name: "Marauders" },
    {show:"Star Trek: Enterprise", season: 2, episode: 7, name: "The Seventh" },
    {show:"Star Trek: Enterprise", season: 2, episode: 8, name: "The Communicator" },
    {show:"Star Trek: Enterprise", season: 2, episode: 9, name: "Singularity" },
    {show:"Star Trek: Enterprise", season: 2, episode: 10, name: "Vanishing Point" },
    {show:"Star Trek: Enterprise", season: 2, episode: 11, name: "Precious Cargo" },
    {show:"Star Trek: Enterprise", season: 2, episode: 12, name: "The Catwalk" },
    {show:"Star Trek: Enterprise", season: 2, episode: 13, name: "Dawn" },
    {show:"Star Trek: Enterprise", season: 2, episode: 14, name: "Stigma" },
    {show:"Star Trek: Enterprise", season: 2, episode: 15, name: "Cease Fire" },
    {show:"Star Trek: Enterprise", season: 2, episode: 16, name: "Future Tense" },
    {show:"Star Trek: Enterprise", season: 2, episode: 17, name: "Canamar" },
    {show:"Star Trek: Enterprise", season: 2, episode: 18, name: "The Crossing" },
    {show:"Star Trek: Enterprise", season: 2, episode: 19, name: "Judgment" },
    {show:"Star Trek: Enterprise", season: 2, episode: 20, name: "Horizon" },
    {show:"Star Trek: Enterprise", season: 2, episode: 21, name: "The Breach" },
    {show:"Star Trek: Enterprise", season: 2, episode: 22, name: "Cogenitor" },
    {show:"Star Trek: Enterprise", season: 2, episode: 23, name: "Regeneration" },
    {show:"Star Trek: Enterprise", season: 2, episode: 24, name: "First Flight" },
    {show:"Star Trek: Enterprise", season: 2, episode: 25, name: "Bounty" },
    {show:"Star Trek: Enterprise", season: 2, episode: 26, name: "The Expanse" },
    {show:"Star Trek: Enterprise", season: 3, episode: 1, name: "The Xindi" },
    {show:"Star Trek: Enterprise", season: 3, episode: 2, name: "Anomaly" },
    {show:"Star Trek: Enterprise", season: 3, episode: 3, name: "Extinction" },
    {show:"Star Trek: Enterprise", season: 3, episode: 4, name: "Rajiin" },
    {show:"Star Trek: Enterprise", season: 3, episode: 5, name: "Impulse" },
    {show:"Star Trek: Enterprise", season: 3, episode: 6, name: "Exile" },
    {show:"Star Trek: Enterprise", season: 3, episode: 7, name: "The Shipment" },
    {show:"Star Trek: Enterprise", season: 3, episode: 8, name: "Twilight" },
    {show:"Star Trek: Enterprise", season: 3, episode: 9, name: "North Star" },
    {show:"Star Trek: Enterprise", season: 3, episode: 10, name: "Similitude" },
    {show:"Star Trek: Enterprise", season: 3, episode: 11, name: "Carpenter Street" },
    {show:"Star Trek: Enterprise", season: 3, episode: 12, name: "Chosen Realm" },
    {show:"Star Trek: Enterprise", season: 3, episode: 13, name: "Proving Ground" },
    {show:"Star Trek: Enterprise", season: 3, episode: 14, name: "Stratagem" },
    {show:"Star Trek: Enterprise", season: 3, episode: 15, name: "Harbinger" },
    {show:"Star Trek: Enterprise", season: 3, episode: 16, name: "Doctor's Orders" },
    {show:"Star Trek: Enterprise", season: 3, episode: 17, name: "Hatchery" },
    {show:"Star Trek: Enterprise", season: 3, episode: 18, name: "Azati Prime" },
    {show:"Star Trek: Enterprise", season: 3, episode: 19, name: "Damage" },
    {show:"Star Trek: Enterprise", season: 3, episode: 20, name: "The Forgotten" },
    {show:"Star Trek: Enterprise", season: 3, episode: 21, name: "E²" },
    {show:"Star Trek: Enterprise", season: 3, episode: 22, name: "The Council" },
    {show:"Star Trek: Enterprise", season: 3, episode: 23, name: "Countdown" },
    {show:"Star Trek: Enterprise", season: 3, episode: 24, name: "Zero Hour" },
    {show:"Star Trek: Enterprise", season: 4, episode: 1, name: "Storm Front, Part I" },
    {show:"Star Trek: Enterprise", season: 4, episode: 2, name: "Storm Front, Part II" },
    {show:"Star Trek: Enterprise", season: 4, episode: 3, name: "Home" },
    {show:"Star Trek: Enterprise", season: 4, episode: 4, name: "Borderland" },
    {show:"Star Trek: Enterprise", season: 4, episode: 5, name: "Cold Station 12" },
    {show:"Star Trek: Enterprise", season: 4, episode: 6, name: "The Augments" },
    {show:"Star Trek: Enterprise", season: 4, episode: 7, name: "The Forge" },
    {show:"Star Trek: Enterprise", season: 4, episode: 8, name: "Awakening" },
    {show:"Star Trek: Enterprise", season: 4, episode: 9, name: "Kir'Shara" },
    {show:"Star Trek: Enterprise", season: 4, episode: 10, name: "Daedalus" },
    {show:"Star Trek: Enterprise", season: 4, episode: 11, name: "Observer Effect" },
    {show:"Star Trek: Enterprise", season: 4, episode: 12, name: "Babel One" },
    {show:"Star Trek: Enterprise", season: 4, episode: 13, name: "United" },
    {show:"Star Trek: Enterprise", season: 4, episode: 14, name: "The Aenar" },
    {show:"Star Trek: Enterprise", season: 4, episode: 15, name: "Affliction" },
    {show:"Star Trek: Enterprise", season: 4, episode: 16, name: "Divergence" },
    {show:"Star Trek: Enterprise", season: 4, episode: 17, name: "Bound" },
    {show:"Star Trek: Enterprise", season: 4, episode: 18, name: "In a Mirror, Darkly, Part I" },
    {show:"Star Trek: Enterprise", season: 4, episode: 19, name: "In a Mirror, Darkly, Part II" },
    {show:"Star Trek: Enterprise", season: 4, episode: 20, name: "Demons" },
    {show:"Star Trek: Enterprise", season: 4, episode: 21, name: "Terra Prime" },
    {show:"Star Trek: Enterprise", season: 4, episode: 22, name: "These Are the Voyages..." }
    ];

const tosEpisodes = [
    {show: "Star Trek: The Original Series", season: 1, episode: 1, name: "The Man Trap" },
    {show: "Star Trek: The Original Series", season: 1, episode: 2, name: "Charlie X" },
    {show: "Star Trek: The Original Series", season: 1, episode: 3, name: "Where No Man Has Gone Before" },
    {show: "Star Trek: The Original Series", season: 1, episode: 4, name: "The Naked Time" },
    {show: "Star Trek: The Original Series", season: 1, episode: 5, name: "The Enemy Within" },
    {show: "Star Trek: The Original Series", season: 1, episode: 6, name: "Mudd's Women" },
    {show: "Star Trek: The Original Series", season: 1, episode: 7, name: "What Are Little Girls Made Of?" },
    {show: "Star Trek: The Original Series", season: 1, episode: 8, name: "Miri" },
    {show: "Star Trek: The Original Series", season: 1, episode: 9, name: "Dagger of the Mind" },
    {show: "Star Trek: The Original Series", season: 1, episode: 10, name: "The Corbomite Maneuver" },
    {show: "Star Trek: The Original Series", season: 1, episode: 11, name: "The Menagerie, Part I" },
    {show: "Star Trek: The Original Series", season: 1, episode: 12, name: "The Menagerie, Part II" },
    {show: "Star Trek: The Original Series", season: 1, episode: 13, name: "The Conscience of the King" },
    {show: "Star Trek: The Original Series", season: 1, episode: 14, name: "Balance of Terror" },
    {show: "Star Trek: The Original Series", season: 1, episode: 15, name: "Shore Leave" },
    {show: "Star Trek: The Original Series", season: 1, episode: 16, name: "The Galileo Seven" },
    {show: "Star Trek: The Original Series", season: 1, episode: 17, name: "The Squire of Gothos" },
    {show: "Star Trek: The Original Series", season: 1, episode: 18, name: "Arena" },
    {show: "Star Trek: The Original Series", season: 1, episode: 19, name: "Tomorrow Is Yesterday" },
    {show: "Star Trek: The Original Series", season: 1, episode: 20, name: "Court Martial" },
    {show: "Star Trek: The Original Series", season: 1, episode: 21, name: "The Return of the Archons" },
    {show: "Star Trek: The Original Series", season: 1, episode: 22, name: "Space Seed" },
    {show: "Star Trek: The Original Series", season: 1, episode: 23, name: "A Taste of Armageddon" },
    {show: "Star Trek: The Original Series", season: 1, episode: 24, name: "This Side of Paradise" },
    {show: "Star Trek: The Original Series", season: 1, episode: 25, name: "The Devil in the Dark" },
    {show: "Star Trek: The Original Series", season: 1, episode: 26, name: "Errand of Mercy" },
    {show: "Star Trek: The Original Series", season: 2, episode: 1, name: "Amok Time" },
    {show: "Star Trek: The Original Series", season: 2, episode: 2, name: "Who Mourns for Adonais?" },
    {show: "Star Trek: The Original Series", season: 2, episode: 3, name: "The Changeling" },
    {show: "Star Trek: The Original Series", season: 2, episode: 4, name: "Mirror, Mirror" },
    {show: "Star Trek: The Original Series", season: 2, episode: 5, name: "The Apple" },
    {show: "Star Trek: The Original Series", season: 2, episode: 6, name: "The Doomsday Machine" },
    {show: "Star Trek: The Original Series", season: 2, episode: 7, name: "Catspaw" },
    {show: "Star Trek: The Original Series", season: 2, episode: 8, name: "I, Mudd" },
    {show: "Star Trek: The Original Series", season: 2, episode: 9, name: "Metamorphosis" },
    {show: "Star Trek: The Original Series", season: 2, episode: 10, name: "Journey to Babel" },
    {show: "Star Trek: The Original Series", season: 2, episode: 11, name: "Friday's Child" },
    {show: "Star Trek: The Original Series", season: 2, episode: 12, name: "The Deadly Years" },
    {show: "Star Trek: The Original Series", season: 2, episode: 13, name: "Obsession" },
    {show: "Star Trek: The Original Series", season: 2, episode: 14, name: "Wolf in the Fold" },
    {show: "Star Trek: The Original Series", season: 2, episode: 15, name: "The Trouble with Tribbles" },
    {show: "Star Trek: The Original Series", season: 2, episode: 16, name: "The Gamesters of Triskelion" },
    {show: "Star Trek: The Original Series", season: 2, episode: 17, name: "A Piece of the Action" },
    {show: "Star Trek: The Original Series", season: 2, episode: 18, name: "The Immunity Syndrome" },
    {show: "Star Trek: The Original Series", season: 2, episode: 19, name: "A Private Little War" },
    {show: "Star Trek: The Original Series", season: 2, episode: 20, name: "Return to Tomorrow" },
    {show: "Star Trek: The Original Series", season: 2, episode: 21, name: "Patterns of Force" },
    {show: "Star Trek: The Original Series", season: 2, episode: 22, name: "By Any Other Name" },
    {show: "Star Trek: The Original Series", season: 2, episode: 23, name: "The Omega Glory" },
    {show: "Star Trek: The Original Series", season: 2, episode: 24, name: "The Ultimate Computer" },
    {show: "Star Trek: The Original Series", season: 2, episode: 25, name: "Bread and Circuses" },
    {show: "Star Trek: The Original Series", season: 2, episode: 26, name: "Assignment: Earth" },
    {show: "Star Trek: The Original Series", season: 3, episode: 1, name: "Spock's Brain" },
    {show: "Star Trek: The Original Series", season: 3, episode: 2, name: "The Enterprise Incident" },
    {show: "Star Trek: The Original Series", season: 3, episode: 4, name: "And the Children Shall Lead" },
    {show: "Star Trek: The Original Series", season: 3, episode: 5, name: "Is There in Truth No Beauty?" },
    {show: "Star Trek: The Original Series", season: 3, episode: 6, name: "Spectre of the Gun" },
    {show: "Star Trek: The Original Series", season: 3, episode: 7, name: "Day of the Dove" },
    {show: "Star Trek: The Original Series", season: 3, episode: 9, name: "The Tholian Web" },
    {show: "Star Trek: The Original Series", season: 3, episode: 10, name: "Plato's Stepchildren" },
    {show: "Star Trek: The Original Series", season: 3, episode: 11, name: "Wink of an Eye" },
    {show: "Star Trek: The Original Series", season: 3, episode: 12, name: "The Empath" },
    {show: "Star Trek: The Original Series", season: 3, episode: 13, name: "Elaan of Troyius" },
    {show: "Star Trek: The Original Series", season: 3, episode: 14, name: "Whom Gods Destroy" },
    {show: "Star Trek: The Original Series", season: 3, episode: 15, name: "Let That Be Your Last Battlefield" },
    {show: "Star Trek: The Original Series", season: 3, episode: 16, name: "The Mark of Gideon" },
    {show: "Star Trek: The Original Series", season: 3, episode: 17, name: "That Which Survives" },
    {show: "Star Trek: The Original Series", season: 3, episode: 18, name: "The Lights of Zetar" },
    {show: "Star Trek: The Original Series", season: 3, episode: 19, name: "Requiem for Methuselah" },
    {show: "Star Trek: The Original Series", season: 3, episode: 20, name: "The Way to Eden" },
    {show: "Star Trek: The Original Series", season: 3, episode: 21, name: "The Cloud Minders" },
    {show: "Star Trek: The Original Series", season: 3, episode: 22, name: "The Savage Curtain" },
    {show: "Star Trek: The Original Series", season: 3, episode: 23, name: "All Our Yesterdays" },
    {show: "Star Trek: The Original Series", season: 3, episode: 24, name: "Turnabout Intruder" }
    ];
const tngEpisodes = [
    { show: "Star Trek: The Next Generation", season: 1, episode: 1, name: "Encounter at Farpoint, Part I" },
    { show: "Star Trek: The Next Generation", season: 1, episode: 2, name: "Encounter at Farpoint, Part II" },
    { show: "Star Trek: The Next Generation", season: 1, episode: 3, name: "The Naked Now" },
    { show: "Star Trek: The Next Generation", season: 1, episode: 4, name: "Code of Honor" },
    { show: "Star Trek: The Next Generation", season: 1, episode: 5, name: "The Last Outpost" },
    { show: "Star Trek: The Next Generation", season: 1, episode: 6, name: "Where No One Has Gone Before" },
    { show: "Star Trek: The Next Generation", season: 1, episode: 7, name: "Lonely Among Us" },
    { show: "Star Trek: The Next Generation", season: 1, episode: 8, name: "Justice" },
    { show: "Star Trek: The Next Generation", season: 1, episode: 9, name: "The Battle" },
    { show: "Star Trek: The Next Generation", season: 1, episode: 10, name: "Hide and Q" },
    { show: "Star Trek: The Next Generation", season: 1, episode: 11, name: "Haven" },
    { show: "Star Trek: The Next Generation", season: 1, episode: 12, name: "The Big Goodbye" },
    { show: "Star Trek: The Next Generation", season: 1, episode: 13, name: "Datalore" },
    { show: "Star Trek: The Next Generation", season: 1, episode: 14, name: "Angel One" },
    { show: "Star Trek: The Next Generation", season: 1, episode: 15, name: "11001001" },
    { show: "Star Trek: The Next Generation", season: 1, episode: 16, name: "Too Short a Season" },
    { show: "Star Trek: The Next Generation", season: 1, episode: 17, name: "When the Bough Breaks" },
    { show: "Star Trek: The Next Generation", season: 1, episode: 18, name: "Home Soil" },
    { show: "Star Trek: The Next Generation", season: 1, episode: 19, name: "Coming of Age" },
    { show: "Star Trek: The Next Generation", season: 1, episode: 20, name: "Heart of Glory" },
    { show: "Star Trek: The Next Generation", season: 1, episode: 21, name: "The Arsenal of Freedom" },
    { show: "Star Trek: The Next Generation", season: 1, episode: 22, name: "Symbiosis" },
    { show: "Star Trek: The Next Generation", season: 1, episode: 23, name: "Skin of Evil" },
    { show: "Star Trek: The Next Generation", season: 1, episode: 24, name: "We'll Always Have Paris" },
    { show: "Star Trek: The Next Generation", season: 1, episode: 25, name: "Conspiracy" },
    { show: "Star Trek: The Next Generation", season: 1, episode: 26, name: "The Neutral Zone" },
    { show: "Star Trek: The Next Generation", season: 2, episode: 1, name: "The Child" },
    { show: "Star Trek: The Next Generation", season: 2, episode: 2, name: "Where Silence Has Lease" },
    { show: "Star Trek: The Next Generation", season: 2, episode: 3, name: "Elementary, Dear Data" },
    { show: "Star Trek: The Next Generation", season: 2, episode: 4, name: "The Outrageous Okona" },
    { show: "Star Trek: The Next Generation", season: 2, episode: 5, name: "Loud as a Whisper" },
    { show: "Star Trek: The Next Generation", season: 2, episode: 6, name: "The Schizoid Man" },
    { show: "Star Trek: The Next Generation", season: 2, episode: 7, name: "Unnatural Selection" },
    { show: "Star Trek: The Next Generation", season: 2, episode: 8, name: "A Matter of Honor" },
    { show: "Star Trek: The Next Generation", season: 2, episode: 9, name: "The Measure of a Man" },
    { show: "Star Trek: The Next Generation", season: 2, episode: 10, name: "The Dauphin" },
    { show: "Star Trek: The Next Generation", season: 2, episode: 11, name: "Contagion" },
    { show: "Star Trek: The Next Generation", season: 2, episode: 12, name: "The Royale" },
    { show: "Star Trek: The Next Generation", season: 2, episode: 13, name: "Time Squared" },
    { show: "Star Trek: The Next Generation", season: 2, episode: 14, name: "The Icarus Factor" },
    { show: "Star Trek: The Next Generation", season: 2, episode: 15, name: "Pen Pals" },
    { show: "Star Trek: The Next Generation", season: 2, episode: 16, name: "Q Who" },
    { show: "Star Trek: The Next Generation", season: 2, episode: 17, name: "Samaritan Snare" },
    { show: "Star Trek: The Next Generation", season: 2, episode: 18, name: "Up the Long Ladder" },
    { show: "Star Trek: The Next Generation", season: 2, episode: 19, name: "Manhunt" },
    { show: "Star Trek: The Next Generation", season: 2, episode: 20, name: "The Emissary" },
    { show: "Star Trek: The Next Generation", season: 2, episode: 21, name: "Peak Performance" },
    { show: "Star Trek: The Next Generation", season: 2, episode: 22, name: "Shades of Gray" },
    { show: "Star Trek: The Next Generation", season: 3, episode: 1, name: "Evolution" },
    { show: "Star Trek: The Next Generation", season: 3, episode: 2, name: "The Ensigns of Command" },
    { show: "Star Trek: The Next Generation", season: 3, episode: 3, name: "The Survivors" },
    { show: "Star Trek: The Next Generation", season: 3, episode: 4, name: "Who Watches the Watchers" },
    { show: "Star Trek: The Next Generation", season: 3, episode: 5, name: "The Bonding" },
    { show: "Star Trek: The Next Generation", season: 3, episode: 6, name: "Booby Trap" },
    { show: "Star Trek: The Next Generation", season: 3, episode: 7, name: "The Enemy" },
    { show: "Star Trek: The Next Generation", season: 3, episode: 8, name: "The Price" },
    { show: "Star Trek: The Next Generation", season: 3, episode: 9, name: "The Vengeance Factor" },
    { show: "Star Trek: The Next Generation", season: 3, episode: 10, name: "The Defector" },
    { show: "Star Trek: The Next Generation", season: 3, episode: 11, name: "The Hunted" },
    { show: "Star Trek: The Next Generation", season: 3, episode: 12, name: "The High Ground" },
    { show: "Star Trek: The Next Generation", season: 3, episode: 13, name: "Deja Q" },
    { show: "Star Trek: The Next Generation", season: 3, episode: 14, name: "A Matter of Perspective" },
    { show: "Star Trek: The Next Generation", season: 3, episode: 15, name: "Yesterday's Enterprise" },
    { show: "Star Trek: The Next Generation", season: 3, episode: 16, name: "The Offspring" },
    { show: "Star Trek: The Next Generation", season: 3, episode: 17, name: "Sins of the Father" },
    { show: "Star Trek: The Next Generation", season: 3, episode: 18, name: "Allegiance" },
    { show: "Star Trek: The Next Generation", season: 3, episode: 19, name: "Captain's Holiday" },
    { show: "Star Trek: The Next Generation", season: 3, episode: 20, name: "Tin Man" },
    { show: "Star Trek: The Next Generation", season: 3, episode: 21, name: "Hollow Pursuits" },
    { show: "Star Trek: The Next Generation", season: 3, episode: 22, name: "The Most Toys" },
    { show: "Star Trek: The Next Generation", season: 3, episode: 23, name: "Sarek" },
    { show: "Star Trek: The Next Generation", season: 3, episode: 24, name: "Ménage à Troi" },
    { show: "Star Trek: The Next Generation", season: 3, episode: 25, name: "Transfigurations" },
    { show: "Star Trek: The Next Generation", season: 3, episode: 26, name: "The Best of Both Worlds: Part 1" },
    { show: "Star Trek: The Next Generation", season: 4, episode: 1, name: "The Best of Both Worlds: Part 2" },
    { show: "Star Trek: The Next Generation", season: 4, episode: 2, name: "Family" },
    { show: "Star Trek: The Next Generation", season: 4, episode: 3, name: "Brothers" },
    { show: "Star Trek: The Next Generation", season: 4, episode: 4, name: "Suddenly Human" },
    { show: "Star Trek: The Next Generation", season: 4, episode: 5, name: "Remember Me" },
    { show: "Star Trek: The Next Generation", season: 4, episode: 6, name: "Legacy" },
    { show: "Star Trek: The Next Generation", season: 4, episode: 7, name: "Reunion" },
    { show: "Star Trek: The Next Generation", season: 4, episode: 8, name: "Future Imperfect" },
    { show: "Star Trek: The Next Generation", season: 4, episode: 9, name: "Final Mission" },
    { show: "Star Trek: The Next Generation", season: 4, episode: 10, name: "The Loss" },
    { show: "Star Trek: The Next Generation", season: 4, episode: 11, name: "Data's Day" },
    { show: "Star Trek: The Next Generation", season: 4, episode: 12, name: "The Wounded" },
    { show: "Star Trek: The Next Generation", season: 4, episode: 13, name: "Devil's Due" },
    { show: "Star Trek: The Next Generation", season: 4, episode: 14, name: "Clues" },
    { show: "Star Trek: The Next Generation", season: 4, episode: 15, name: "First Contact" },
    { show: "Star Trek: The Next Generation", season: 4, episode: 16, name: "Galaxy's Child" },
    { show: "Star Trek: The Next Generation", season: 4, episode: 17, name: "Night Terrors" },
    { show: "Star Trek: The Next Generation", season: 4, episode: 18, name: "Identity Crisis" },
    { show: "Star Trek: The Next Generation", season: 4, episode: 19, name: "The Nth Degree" },
    { show: "Star Trek: The Next Generation", season: 4, episode: 20, name: "Qpid" },
    { show: "Star Trek: The Next Generation", season: 4, episode: 21, name: "The Drumhead" },
    { show: "Star Trek: The Next Generation", season: 4, episode: 22, name: "Half a Life" },
    { show: "Star Trek: The Next Generation", season: 4, episode: 23, name: "The Host" },
    { show: "Star Trek: The Next Generation", season: 4, episode: 24, name: "The Mind's Eye" },
    { show: "Star Trek: The Next Generation", season: 4, episode: 25, name: "In Theory" },
    { show: "Star Trek: The Next Generation", season: 4, episode: 26, name: "Redemption: Part 1" },
    { show: "Star Trek: The Next Generation", season: 5, episode: 1, name: "Redemption: Part 2" },
    { show: "Star Trek: The Next Generation", season: 5, episode: 2, name: "Darmok" },
    { show: "Star Trek: The Next Generation", season: 5, episode: 3, name: "Ensign Ro" },
    { show: "Star Trek: The Next Generation", season: 5, episode: 4, name: "Silicon Avatar" },
    { show: "Star Trek: The Next Generation", season: 5, episode: 5, name: "Disaster" },
    { show: "Star Trek: The Next Generation", season: 5, episode: 6, name: "The Game" },
    { show: "Star Trek: The Next Generation", season: 5, episode: 7, name: "Unification: Part 1" },
    { show: "Star Trek: The Next Generation", season: 5, episode: 8, name: "Unification: Part 2" },
    { show: "Star Trek: The Next Generation", season: 5, episode: 9, name: "A Matter of Time" },
    { show: "Star Trek: The Next Generation", season: 5, episode: 10, name: "New Ground" },
    { show: "Star Trek: The Next Generation", season: 5, episode: 11, name: "Hero Worship" },
    { show: "Star Trek: The Next Generation", season: 5, episode: 12, name: "Violations" },
    { show: "Star Trek: The Next Generation", season: 5, episode: 13, name: "The Masterpiece Society" },
    { show: "Star Trek: The Next Generation", season: 5, episode: 14, name: "Conundrum" },
    { show: "Star Trek: The Next Generation", season: 5, episode: 15, name: "Power Play" },
    { show: "Star Trek: The Next Generation", season: 5, episode: 16, name: "Ethics" },
{ show: "Star Trek: The Next Generation", season: 5, episode: 17, name: "The Outcast" },
{ show: "Star Trek: The Next Generation", season: 5, episode: 18, name: "Cause and Effect" },
{ show: "Star Trek: The Next Generation", season: 5, episode: 19, name: "The First Duty" },
{ show: "Star Trek: The Next Generation", season: 5, episode: 20, name: "Cost of Living" },
{ show: "Star Trek: The Next Generation", season: 5, episode: 21, name: "The Perfect Mate" },
{ show: "Star Trek: The Next Generation", season: 5, episode: 22, name: "Imaginary Friend" },
{ show: "Star Trek: The Next Generation", season: 5, episode: 23, name: "I Borg" },
{ show: "Star Trek: The Next Generation", season: 5, episode: 24, name: "The Next Phase" },
{ show: "Star Trek: The Next Generation", season: 5, episode: 25, name: "The Inner Light" },
{ show: "Star Trek: The Next Generation", season: 5, episode: 26, name: "Time's Arrow: Part 1" },
{ show: "Star Trek: The Next Generation", season: 6, episode: 1, name: "Time's Arrow: Part 2" },
{ show: "Star Trek: The Next Generation", season: 6, episode: 2, name: "Realm of Fear" },
{ show: "Star Trek: The Next Generation", season: 6, episode: 3, name: "Man of the People" },
{ show: "Star Trek: The Next Generation", season: 6, episode: 4, name: "Relics" },
{ show: "Star Trek: The Next Generation", season: 6, episode: 5, name: "Schisms" },
{ show: "Star Trek: The Next Generation", season: 6, episode: 6, name: "True Q" },
{ show: "Star Trek: The Next Generation", season: 6, episode: 7, name: "Rascals" },
{ show: "Star Trek: The Next Generation", season: 6, episode: 8, name: "A Fistful of Datas" },
{ show: "Star Trek: The Next Generation", season: 6, episode: 9, name: "The Quality of Life" },
{ show: "Star Trek: The Next Generation", season: 6, episode: 10, name: "Chain of Command: Part 1" },
{ show: "Star Trek: The Next Generation", season: 6, episode: 11, name: "Chain of Command: Part 2" },
{ show: "Star Trek: The Next Generation", season: 6, episode: 12, name: "Ship in a Bottle" },
{ show: "Star Trek: The Next Generation", season: 6, episode: 13, name: "Aquiel" },
{ show: "Star Trek: The Next Generation", season: 6, episode: 14, name: "Face of the Enemy" },
{ show: "Star Trek: The Next Generation", season: 6, episode: 15, name: "Tapestry" },
{ show: "Star Trek: The Next Generation", season: 6, episode: 16, name: "Birthright: Part 1" },
{ show: "Star Trek: The Next Generation", season: 6, episode: 17, name: "Birthright: Part 2" },
{ show: "Star Trek: The Next Generation", season: 6, episode: 18, name: "Starship Mine" },
{ show: "Star Trek: The Next Generation", season: 6, episode: 19, name: "Lessons" },
{ show: "Star Trek: The Next Generation", season: 6, episode: 20, name: "The Chase" },
{ show: "Star Trek: The Next Generation", season: 6, episode: 21, name: "Frame of Mind" },
{ show: "Star Trek: The Next Generation", season: 6, episode: 22, name: "Suspicions" },
{ show: "Star Trek: The Next Generation", season: 6, episode: 23, name: "Rightful Heir" },
{ show: "Star Trek: The Next Generation", season: 6, episode: 24, name: "Second Chances" },
{ show: "Star Trek: The Next Generation", season: 6, episode: 25, name: "Timescape" },
{ show: "Star Trek: The Next Generation", season: 6, episode: 26, name: "Descent: Part 1" },
{ show: "Star Trek: The Next Generation", season: 7, episode: 1, name: "Descent: Part 2" },
{ show: "Star Trek: The Next Generation", season: 7, episode: 2, name: "Liaisons" },
{ show: "Star Trek: The Next Generation", season: 7, episode: 3, name: "Interface" },
{ show: "Star Trek: The Next Generation", season: 7, episode: 4, name: "Gambit: Part 1" },
{ show: "Star Trek: The Next Generation", season: 7, episode: 5, name: "Gambit: Part 2" },
{ show: "Star Trek: The Next Generation", season: 7, episode: 6, name: "Phantasms" },
{ show: "Star Trek: The Next Generation", season: 7, episode: 7, name: "Dark Page" },
{ show: "Star Trek: The Next Generation", season: 7, episode: 8, name: "Attached" },
{ show: "Star Trek: The Next Generation", season: 7, episode: 9, name: "Force of Nature" },
{ show: "Star Trek: The Next Generation", season: 7, episode: 10, name: "Inheritance" },
{ show: "Star Trek: The Next Generation", season: 7, episode: 11, name: "Parallels" },
{ show: "Star Trek: The Next Generation", season: 7, episode: 12, name: "The Pegasus" },
{ show: "Star Trek: The Next Generation", season: 7, episode: 13, name: "Homeward" },
{ show: "Star Trek: The Next Generation", season: 7, episode: 14, name: "Sub Rosa" },
{ show: "Star Trek: The Next Generation", season: 7, episode: 15, name: "Lower Decks" },
{ show: "Star Trek: The Next Generation", season: 7, episode: 16, name: "Thine Own Self" },
{ show: "Star Trek: The Next Generation", season: 7, episode: 17, name: "Masks" },
{ show: "Star Trek: The Next Generation", season: 7, episode: 18, name: "Eye of the Beholder" },
{ show: "Star Trek: The Next Generation", season: 7, episode: 19, name: "Genesis" },
{ show: "Star Trek: The Next Generation", season: 7, episode: 20, name: "Journey's End" },
{ show: "Star Trek: The Next Generation", season: 7, episode: 21, name: "Firstborn" },
{ show: "Star Trek: The Next Generation", season: 7, episode: 22, name: "Bloodlines" },
{ show: "Star Trek: The Next Generation", season: 7, episode: 23, name: "Emergence" },
{ show: "Star Trek: The Next Generation", season: 7, episode: 24, name: "Preemptive Strike" },
{ show: "Star Trek: The Next Generation", season: 7, episode: 25, name: "All Good Things..." },
];

const ds9Episodes = [
    { show: "Star Trek: Deep Space Nine", season: 1, episode: 1, name: "Emissary" },
    { show: "Star Trek: Deep Space Nine", season: 1, episode: 2, name: "Past Prologue" },
    { show: "Star Trek: Deep Space Nine", season: 1, episode: 3, name: "A Man Alone" },
    { show: "Star Trek: Deep Space Nine", season: 1, episode: 4, name: "Babel" },
    { show: "Star Trek: Deep Space Nine", season: 1, episode: 5, name: "Captive Pursuit" },
    { show: "Star Trek: Deep Space Nine", season: 1, episode: 6, name: "Q-Less" },
    { show: "Star Trek: Deep Space Nine", season: 1, episode: 7, name: "Dax" },
    { show: "Star Trek: Deep Space Nine", season: 1, episode: 8, name: "The Passenger" },
    { show: "Star Trek: Deep Space Nine", season: 1, episode: 9, name: "Move Along Home" },
    { show: "Star Trek: Deep Space Nine", season: 1, episode: 10, name: "The Nagus" },
    { show: "Star Trek: Deep Space Nine", season: 1, episode: 11, name: "Vortex" },
    { show: "Star Trek: Deep Space Nine", season: 1, episode: 12, name: "Battle Lines" },
    { show: "Star Trek: Deep Space Nine", season: 1, episode: 13, name: "The Storyteller" },
    { show: "Star Trek: Deep Space Nine", season: 1, episode: 14, name: "Progress" },
    { show: "Star Trek: Deep Space Nine", season: 1, episode: 15, name: "If Wishes Were Horses" },
    { show: "Star Trek: Deep Space Nine", season: 1, episode: 16, name: "The Forsaken" },
    { show: "Star Trek: Deep Space Nine", season: 1, episode: 17, name: "Dramatis Personae" },
    { show: "Star Trek: Deep Space Nine", season: 1, episode: 18, name: "Duet" },
    { show: "Star Trek: Deep Space Nine", season: 1, episode: 19, name: "In the Hands of the Prophets" },
    { show: "Star Trek: Deep Space Nine", season: 2, episode: 1, name: "The Homecoming" },
    { show: "Star Trek: Deep Space Nine", season: 2, episode: 2, name: "The Circle" },
    { show: "Star Trek: Deep Space Nine", season: 2, episode: 3, name: "The Siege" },
    { show: "Star Trek: Deep Space Nine", season: 2, episode: 4, name: "Invasive Procedures" },
    { show: "Star Trek: Deep Space Nine", season: 2, episode: 5, name: "Cardassians" },
    { show: "Star Trek: Deep Space Nine", season: 2, episode: 6, name: "Melora" },
    { show: "Star Trek: Deep Space Nine", season: 2, episode: 7, name: "Rules of Acquisition" },
    { show: "Star Trek: Deep Space Nine", season: 2, episode: 8, name: "Necessary Evil" },
    { show: "Star Trek: Deep Space Nine", season: 2, episode: 9, name: "Second Sight"},
    { show: "Star Trek: Deep Space Nine", season: 2, episode: 10, name: "Sanctuary" },
    { show: "Star Trek: Deep Space Nine", season: 2, episode: 11, name: "Rivals" },
    { show: "Star Trek: Deep Space Nine", season: 2, episode: 12, name: "The Alternate" },
    { show: "Star Trek: Deep Space Nine", season: 2, episode: 13, name: "Armageddon Game" },
    { show: "Star Trek: Deep Space Nine", season: 2, episode: 14, name: "Whispers" },
    { show: "Star Trek: Deep Space Nine", season: 2, episode: 15, name: "Paradise" },
    { show: "Star Trek: Deep Space Nine", season: 2, episode: 16, name: "Shadowplay" },
    { show: "Star Trek: Deep Space Nine", season: 2, episode: 17, name: "Playing God" },
    { show: "Star Trek: Deep Space Nine", season: 2, episode: 18, name: "Profit and Loss" },
    { show: "Star Trek: Deep Space Nine", season: 2, episode: 19, name: "Blood Oath" },
    { show: "Star Trek: Deep Space Nine", season: 2, episode: 20, name: "The Maquis, Part I" },
    { show: "Star Trek: Deep Space Nine", season: 2, episode: 21, name: "The Maquis, Part II" },
    { show: "Star Trek: Deep Space Nine", season: 2, episode: 22, name: "The Wire" },
    { show: "Star Trek: Deep Space Nine", season: 2, episode: 23, name: "Crossover" },
    { show: "Star Trek: Deep Space Nine", season: 2, episode: 24, name: "The Collaborator" },
    { show: "Star Trek: Deep Space Nine", season: 2, episode: 25, name: "Tribunal" },
    { show: "Star Trek: Deep Space Nine", season: 2, episode: 26, name: "The Jem'Hadar" },
    { show: "Star Trek: Deep Space Nine", season: 3, episode: 1, name: "The Search, Part I" },
    { show: "Star Trek: Deep Space Nine", season: 3, episode: 2, name: "The Search, Part II" },
    { show: "Star Trek: Deep Space Nine", season: 3, episode: 3, name: "The House of Quark" },
    { show: "Star Trek: Deep Space Nine", season: 3, episode: 4, name: "Equilibrium" },
    { show: "Star Trek: Deep Space Nine", season: 3, episode: 5, name: "Second Skin" },
    { show: "Star Trek: Deep Space Nine", season: 3, episode: 6, name: "The Abandoned" },
    { show: "Star Trek: Deep Space Nine", season: 3, episode: 7, name: "Civil Defense" },
    { show: "Star Trek: Deep Space Nine", season: 3, episode: 8, name: "Meridian" },
    { show: "Star Trek: Deep Space Nine", season: 3, episode: 9, name: "Defiant" },
    { show: "Star Trek: Deep Space Nine", season: 3, episode: 10, name: "Fascination" },
    { show: "Star Trek: Deep Space Nine", season: 3, episode: 11, name: "Past Tense, Part I" },
    { show: "Star Trek: Deep Space Nine", season: 3, episode: 12, name: "Past Tense, Part II" },
    { show: "Star Trek: Deep Space Nine", season: 3, episode: 13, name: "Life Support" },
    { show: "Star Trek: Deep Space Nine", season: 3, episode: 14, name: "Heart of Stone" },
    { show: "Star Trek: Deep Space Nine", season: 3, episode: 15, name: "Destiny" },
    { show: "Star Trek: Deep Space Nine", season: 3, episode: 16, name: "Prophet Motive" },
    { show: "Star Trek: Deep Space Nine", season: 3, episode: 17, name: "Visionary" },
    { show: "Star Trek: Deep Space Nine", season: 3, episode: 18, name: "Distant Voices" },
    { show: "Star Trek: Deep Space Nine", season: 3, episode: 19, name: "Through the Looking Glass" },
    { show: "Star Trek: Deep Space Nine", season: 3, episode: 20, name: "Improbable Cause" },
    { show: "Star Trek: Deep Space Nine", season: 3, episode: 21, name: "The Die is Cast" },
    { show: "Star Trek: Deep Space Nine", season: 3, episode: 22, name: "Explorers" },
    { show: "Star Trek: Deep Space Nine", season: 3, episode: 23, name: "Family Business" },
    { show: "Star Trek: Deep Space Nine", season: 3, episode: 24, name: "Shakaar" },
    { show: "Star Trek: Deep Space Nine", season: 3, episode: 25, name: "Facets" },
    { show: "Star Trek: Deep Space Nine", season: 3, episode: 26, name: "The Adversary" },
    { show: "Star Trek: Deep Space Nine", season: 4, episode: 1, name: "The Way of the Warrior, Part I" },
    { show: "Star Trek: Deep Space Nine", season: 4, episode: 2, name: "The Way of the Warrior, Part II" },
    { show: "Star Trek: Deep Space Nine", season: 4, episode: 3, name: "The Visitor" },
    { show: "Star Trek: Deep Space Nine", season: 4, episode: 4, name: "Hippocratic Oath" },
    { show: "Star Trek: Deep Space Nine", season: 4, episode: 5, name: "Indiscretion" },
    { show: "Star Trek: Deep Space Nine", season: 4, episode: 6, name: "Rejoined" },
    { show: "Star Trek: Deep Space Nine", season: 4, episode: 7, name: "Starship Down" },
    { show: "Star Trek: Deep Space Nine", season: 4, episode: 8, name: "Little Green Men" },
    { show: "Star Trek: Deep Space Nine", season: 4, episode: 9, name: "The Sword of Kahless" },
    { show: "Star Trek: Deep Space Nine", season: 4, episode: 10, name: "Our Man Bashir" },
    { show: "Star Trek: Deep Space Nine", season: 4, episode: 11, name: "Homefront" },
    { show: "Star Trek: Deep Space Nine", season: 4, episode: 12, name: "Paradise Lost" },
    { show: "Star Trek: Deep Space Nine", season: 4, episode: 13, name: "Crossfire" },
    { show: "Star Trek: Deep Space Nine", season: 4, episode: 14, name: "Return to Grace" },
    { show: "Star Trek: Deep Space Nine", season: 4, episode: 15, name: "Sons of Mogh" },
    { show: "Star Trek: Deep Space Nine", season: 4, episode: 16, name: "Bar Association" },
    { show: "Star Trek: Deep Space Nine", season: 4, episode: 17, name: "Accession" },
    { show: "Star Trek: Deep Space Nine", season: 4, episode: 18, name: "Rules of Engagement" },
    { show: "Star Trek: Deep Space Nine", season: 4, episode: 19, name: "Hard Time" },
    { show: "Star Trek: Deep Space Nine", season: 4, episode: 20, name: "Shattered Mirror" },
    { show: "Star Trek: Deep Space Nine", season: 4, episode: 21, name: "The Muse" },
    { show: "Star Trek: Deep Space Nine", season: 4, episode: 22, name: "For the Cause" },
    { show: "Star Trek: Deep Space Nine", season: 4, episode: 23, name: "To the Death" },
    { show: "Star Trek: Deep Space Nine", season: 4, episode: 24, name: "The Quickening" },
    { show: "Star Trek: Deep Space Nine", season: 4, episode: 25, name: "Body Parts" },
    { show: "Star Trek: Deep Space Nine", season: 4, episode: 26, name: "Broken Link" },
    { show: "Star Trek: Deep Space Nine", season: 5, episode: 1, name: "Apocalypse Rising" },
    { show: "Star Trek: Deep Space Nine", season: 5, episode: 2, name: "The Ship" },
    { show: "Star Trek: Deep Space Nine", season: 5, episode: 3, name: "Looking for par'Mach in All the Wrong Places" },
    { show: "Star Trek: Deep Space Nine", season: 5, episode: 4, name: "Nor the Battle to the Strong" },
    { show: "Star Trek: Deep Space Nine", season: 5, episode: 5, name: "The Assignment" },
    { show: "Star Trek: Deep Space Nine", season: 5, episode: 6, name: "Trials and Tribble-ations" },
    { show: "Star Trek: Deep Space Nine", season: 5, episode: 7, name: "Let He Who Is Without Sin..." },
    { show: "Star Trek: Deep Space Nine", season: 5, episode: 8, name: "Things Past" },
    { show: "Star Trek: Deep Space Nine", season: 5, episode: 9, name: "The Ascent" },
    { show: "Star Trek: Deep Space Nine", season: 5, episode: 10, name: "Rapture" },
    { show: "Star Trek: Deep Space Nine", season: 5, episode: 11, name: "The Darkness and the Light" },
    { show: "Star Trek: Deep Space Nine", season: 5, episode: 12, name: "The Begotten" },
    { show: "Star Trek: Deep Space Nine", season: 5, episode: 13, name: "For the Uniform" },
    { show: "Star Trek: Deep Space Nine", season: 5, episode: 14, name: "In Purgatory's Shadow" },
    { show: "Star Trek: Deep Space Nine", season: 5, episode: 15, name: "By Inferno's Light" },
    { show: "Star Trek: Deep Space Nine", season: 5, episode: 16, name: "Doctor Bashir, I Presume?" },
    { show: "Star Trek: Deep Space Nine", season: 5, episode: 17, name: "A Simple Investigation" },
    { show: "Star Trek: Deep Space Nine", season: 5, episode: 18, name: "Business as Usual" },
    { show: "Star Trek: Deep Space Nine", season: 5, episode: 19, name: "Ties of Blood and Water" },
    { show: "Star Trek: Deep Space Nine", season: 5, episode: 20, name: "Ferengi Love Songs" },
    { show: "Star Trek: Deep Space Nine", season: 5, episode: 21, name: "Soldiers of the Empire" },
    { show: "Star Trek: Deep Space Nine", season: 5, episode: 22, name: "Children of Time" },
    { show: "Star Trek: Deep Space Nine", season: 5, episode: 23, name: "Blaze of Glory" },
    { show: "Star Trek: Deep Space Nine", season: 5, episode: 24, name: "Empok Nor" },
    { show: "Star Trek: Deep Space Nine", season: 5, episode: 25, name: "In the Cards" },
    { show: "Star Trek: Deep Space Nine", season: 5, episode: 26, name: "Call to Arms" },
    { show: "Star Trek: Deep Space Nine", season: 6, episode: 1, name: 'A Time to Stand' },
    { show: "Star Trek: Deep Space Nine", season: 6, episode: 2, name: 'Rocks and Shoals' },
    { show: "Star Trek: Deep Space Nine", season: 6, episode: 3, name: 'Sons and Daughters' },
    { show: "Star Trek: Deep Space Nine", season: 6, episode: 4, name: 'Behind the Lines' },
    { show: "Star Trek: Deep Space Nine", season: 6, episode: 5, name: 'Favor the Bold' },
    { show: "Star Trek: Deep Space Nine", season: 6, episode: 6, name: 'Sacrifice of Angels' },
    { show: "Star Trek: Deep Space Nine", season: 6, episode: 7, name: 'You Are Cordially Invited' },
    { show: "Star Trek: Deep Space Nine", season: 6, episode: 8, name: 'Resurrection' },
    { show: "Star Trek: Deep Space Nine", season: 6, episode: 9, name: 'Statistical Probabilities' },
    { show: "Star Trek: Deep Space Nine", season: 6, episode: 10, name: "The Magnificent Ferengi" },
    { show: "Star Trek: Deep Space Nine", season: 6, episode: 11, name: "Waltz" },
    { show: "Star Trek: Deep Space Nine", season: 6, episode: 12, name: "Who Mourns for Morn?" },
    { show: "Star Trek: Deep Space Nine", season: 6, episode: 13, name: "Far Beyond the Stars" },
    { show: "Star Trek: Deep Space Nine", season: 6, episode: 14, name: "One Little Ship" },
    { show: "Star Trek: Deep Space Nine", season: 6, episode: 15, name: "Honor Among Thieves" },
    { show: "Star Trek: Deep Space Nine", season: 6, episode: 16, name: "Change of Heart" },
    { show: "Star Trek: Deep Space Nine", season: 6, episode: 17, name: "Wrongs Darker Than Death or Night" },
    { show: "Star Trek: Deep Space Nine", season: 6, episode: 18, name: "Inquisition" },
    { show: "Star Trek: Deep Space Nine", season: 6, episode: 19, name: "In the Pale Moonlight" },
    { show: "Star Trek: Deep Space Nine", season: 6, episode: 20, name: "His Way" },
    { show: "Star Trek: Deep Space Nine", season: 6, episode: 21, name: "The Reckoning" },
    { show: "Star Trek: Deep Space Nine", season: 6, episode: 22, name: "Valiant" },
    { show: "Star Trek: Deep Space Nine", season: 6, episode: 23, name: "Profit and Lace" },
    { show: "Star Trek: Deep Space Nine", season: 6, episode: 24, name: "Time's Orphan" },
    { show: "Star Trek: Deep Space Nine", season: 6, episode: 25, name: "The Sound of Her Voice" },
    { show: "Star Trek: Deep Space Nine", season: 6, episode: 26, name: "Tears of the Prophets" },
    { show: "Star Trek: Deep Space Nine", season: 7, episode: 1, name: "Image in the Sand" },
    { show: "Star Trek: Deep Space Nine", season: 7, episode: 2, name: "Shadows and Symbols" },
    { show: "Star Trek: Deep Space Nine", season: 7, episode: 3, name: "Afterimage" },
    { show: "Star Trek: Deep Space Nine", season: 7, episode: 4, name: "Take Me Out to the Holosuite" },
    { show: "Star Trek: Deep Space Nine", season: 7, episode: 5, name: "Chrysalis" },
    { show: "Star Trek: Deep Space Nine", season: 7, episode: 6, name: "Treachery, Faith, and the Great River" },
    { show: "Star Trek: Deep Space Nine", season: 7, episode: 7, name: "Once More Unto the Breach" },
    { show: "Star Trek: Deep Space Nine", season: 7, episode: 8, name: "The Siege of AR-558" },
    { show: "Star Trek: Deep Space Nine", season: 7, episode: 9, name: "Covenant" },
    { show: "Star Trek: Deep Space Nine", season: 7, episode: 10, name: "It's Only a Paper Moon" },
    { show: "Star Trek: Deep Space Nine", season: 7, episode: 11, name: "Prodigal Daughter" },
    { show: "Star Trek: Deep Space Nine", season: 7, episode: 12, name: "The Emperor's New Cloak" },
    { show: "Star Trek: Deep Space Nine", season: 7, episode: 13, name: "Field of Fire" },
    { show: "Star Trek: Deep Space Nine", season: 7, episode: 14, name: "Chimera" },
    { show: "Star Trek: Deep Space Nine", season: 7, episode: 15, name: "Badda-Bing Badda-Bang" },
    { show: "Star Trek: Deep Space Nine", season: 7, episode: 16, name: "Inter Arma Enim Silent Leges" },
    { show: "Star Trek: Deep Space Nine", season: 7, episode: 17, name: "Penumbra" },
    { show: "Star Trek: Deep Space Nine", season: 7, episode: 18, name: "'Til Death Do Us Part" },
    { show: "Star Trek: Deep Space Nine", season: 7, episode: 19, name: "Strange Bedfellows" },
    { show: "Star Trek: Deep Space Nine", season: 7, episode: 20, name: "The Changing Face of Evil" },
    { show: "Star Trek: Deep Space Nine", season: 7, episode: 21, name: "When It Rains..." },
    { show: "Star Trek: Deep Space Nine", season: 7, episode: 22, name: "Tacking Into the Wind" },
    { show: "Star Trek: Deep Space Nine", season: 7, episode: 23, name: "Extreme Measures" },
    { show: "Star Trek: Deep Space Nine", season: 7, episode: 24, name: "The Dogs of War" },
    { show: "Star Trek: Deep Space Nine", season: 7, episode: 25, name: "What You Leave Behind, Part I" },
    { show: "Star Trek: Deep Space Nine", season: 7, episode: 26, name: "What You Leave Behind, Part II" },
  ];

  const voyEpisodes = [
    { show: "Star Trek: Voyager", season: 1, episode: 1, name: 'Caretaker, Part I' },
    { show: "Star Trek: Voyager", season: 1, episode: 2, name: 'Caretaker, Part II' },
    { show: "Star Trek: Voyager", season: 1, episode: 3, name: 'Parallax' },
    { show: "Star Trek: Voyager", season: 1, episode: 4, name: 'Time and Again' },
    { show: "Star Trek: Voyager", season: 1, episode: 5, name: 'Phage' },
    { show: "Star Trek: Voyager", season: 1, episode: 6, name: 'The Cloud' },
    { show: "Star Trek: Voyager", season: 1, episode: 7, name: 'Eye of the Needle' },
    { show: "Star Trek: Voyager", season: 1, episode: 8, name: 'Ex Post Facto' },
    { show: "Star Trek: Voyager", season: 1, episode: 9, name: 'Emanations' },
    { show: "Star Trek: Voyager", season: 1, episode: 10, name: 'Prime Factors' },
    { show: "Star Trek: Voyager", season: 1, episode: 11, name: 'State of Flux' },
    { show: "Star Trek: Voyager", season: 1, episode: 12, name: 'Heroes and Demons' },
    { show: "Star Trek: Voyager", season: 1, episode: 13, name: 'Cathexis' },
    { show: "Star Trek: Voyager", season: 1, episode: 14, name: 'Faces' },
    { show: "Star Trek: Voyager", season: 1, episode: 15, name: 'Jetrel' },
    { show: "Star Trek: Voyager", season: 1, episode: 16, name: 'Learning Curve' },
    { show: "Star Trek: Voyager", season: 2, episode: 1, name: 'The 37s' },
    { show: "Star Trek: Voyager", season: 2, episode: 2, name: 'Initiations' },
    { show: "Star Trek: Voyager", season: 2, episode: 3, name: 'Projections' },
    { show: "Star Trek: Voyager", season: 2, episode: 4, name: 'Elogium' },
    { show: "Star Trek: Voyager", season: 2, episode: 5, name: 'Non Sequitur' },
    { show: "Star Trek: Voyager", season: 2, episode: 6, name: 'Twisted' },
    { show: "Star Trek: Voyager", season: 2, episode: 7, name: 'Parturition' },
    { show: "Star Trek: Voyager", season: 2, episode: 8, name: 'Persistence of Vision' },
    { show: "Star Trek: Voyager", season: 2, episode: 9, name: 'Tattoo' },
    { show: "Star Trek: Voyager", season: 2, episode: 10, name: 'Cold Fire' },
    { show: "Star Trek: Voyager", season: 2, episode: 11, name: 'Maneuvers' },
    { show: "Star Trek: Voyager", season: 2, episode: 12, name: "Resistance" },
    { show: "Star Trek: Voyager", season: 2, episode: 13, name: "Prototype" },
    { show: "Star Trek: Voyager", season: 2, episode: 14, name: "Alliances" },
    { show: "Star Trek: Voyager", season: 2, episode: 15, name: "Threshold" },
    { show: "Star Trek: Voyager", season: 2, episode: 16, name: "Meld" },
    { show: "Star Trek: Voyager", season: 2, episode: 17, name: "Dreadnought" },
    { show: "Star Trek: Voyager", season: 2, episode: 18, name: "Death Wish" },
    { show: "Star Trek: Voyager", season: 2, episode: 19, name: "Lifesigns" },
    { show: "Star Trek: Voyager", season: 2, episode: 20, name: "Investigations" },
    { show: "Star Trek: Voyager", season: 2, episode: 21, name: "Deadlock" },
    { show: "Star Trek: Voyager", season: 2, episode: 22, name: "Innocence" },
    { show: "Star Trek: Voyager", season: 2, episode: 23, name: "The Thaw" },
    { show: "Star Trek: Voyager", season: 2, episode: 24, name: "Tuvix" },
    { show: "Star Trek: Voyager", season: 2, episode: 25, name: "Resolutions" },
    { show: "Star Trek: Voyager", season: 2, episode: 26, name: "Basics, Part I" },
    { show: "Star Trek: Voyager", season: 3, episode: 1, name: "Basics, Part II" },
    { show: "Star Trek: Voyager", season: 3, episode: 2, name: "Flashback" },
    { show: "Star Trek: Voyager", season: 3, episode: 3, name: "The Chute" },
    { show: "Star Trek: Voyager", season: 3, episode: 4, name: "The Swarm" },
    { show: "Star Trek: Voyager", season: 3, episode: 5, name: "False Profits" },
    { show: "Star Trek: Voyager", season: 3, episode: 6, name: "Remember" },
    { show: "Star Trek: Voyager", season: 3, episode: 7, name: "Sacred Ground" },
    { show: "Star Trek: Voyager", season: 3, episode: 8, name: "Future's End, Part I" },
    { show: "Star Trek: Voyager", season: 3, episode: 9, name: "Future's End, Part II" },
    { show: "Star Trek: Voyager", season: 3, episode: 10, name: "Warlord" },
    { show: "Star Trek: Voyager", season: 3, episode: 11, name: "The Q and the Grey" },
    { show: "Star Trek: Voyager", season: 3, episode: 12, name: "Macrocosm"},
    { show: "Star Trek: Voyager", season: 3, episode: 13, name: "Fair Trade" },
    { show: "Star Trek: Voyager", season: 3, episode: 14, name: "Alter Ego" },
    { show: "Star Trek: Voyager", season: 3, episode: 15, name: "Coda" },
    { show: "Star Trek: Voyager", season: 3, episode: 16, name: "Blood Fever" },
    { show: "Star Trek: Voyager", season: 3, episode: 17, name: "Unity" },
    { show: "Star Trek: Voyager", season: 3, episode: 18, name: "Darkling" },
    { show: "Star Trek: Voyager", season: 3, episode: 19, name: "Rise" },
    { show: "Star Trek: Voyager", season: 3, episode: 20, name: "Favorite Son" },
    { show: "Star Trek: Voyager", season: 3, episode: 21, name: "Before and After" },
    { show: "Star Trek: Voyager", season: 3, episode: 22, name: "Real Life" },
    { show: "Star Trek: Voyager", season: 3, episode: 23, name: "Distant Origin" },
    { show: "Star Trek: Voyager", season: 3, episode: 24, name: "Displaced" },
    { show: "Star Trek: Voyager", season: 3, episode: 25, name: "Worst Case Scenario" },
    { show: "Star Trek: Voyager", season: 3, episode: 26, name: "Scorpion, Part I" },
    { show: "Star Trek: Voyager", season: 4, episode: 1, name: "Scorpion, Part II" },
    { show: "Star Trek: Voyager", season: 4, episode: 2, name: "The Gift" },
    { show: "Star Trek: Voyager", season: 4, episode: 3, name: "Day of Honor" },
    { show: "Star Trek: Voyager", season: 4, episode: 4, name: "Nemesis" },
    { show: "Star Trek: Voyager", season: 4, episode: 5, name: "Revulsion" },
    { show: "Star Trek: Voyager", season: 4, episode: 6, name: "The Raven" },
    { show: "Star Trek: Voyager", season: 4, episode: 7, name: "Scientific Method" },
    { show: "Star Trek: Voyager", season: 4, episode: 8, name: "Year of Hell, Part I" },
    { show: "Star Trek: Voyager", season: 4, episode: 9, name: "Year of Hell, Part II" },
    { show: "Star Trek: Voyager", season: 4, episode: 10, name: "Random Thoughts" },
    { show: "Star Trek: Voyager", season: 4, episode: 11, name: "Concerning Flight" },
    { show: "Star Trek: Voyager", season: 4, episode: 12, name: "Mortal Coil" },
    { show: "Star Trek: Voyager", season: 4, episode: 13, name: "Waking Moments" },
    { show: "Star Trek: Voyager", season: 4, episode: 14, name: "Message in a Bottle" },
    { show: "Star Trek: Voyager", season: 4, episode: 15, name: "Hunters" },
    { show: "Star Trek: Voyager", season: 4, episode: 16, name: "Prey" },
    { show: "Star Trek: Voyager", season: 4, episode: 17, name: "Retrospect" },
    { show: "Star Trek: Voyager", season: 4, episode: 18, name: "The Killing Game, Part I" },
    { show: "Star Trek: Voyager", season: 4, episode: 19, name: "The Killing Game, Part II" },
    { show: "Star Trek: Voyager", season: 4, episode: 20, name: "Vis à Vis" },
    { show: "Star Trek: Voyager", season: 4, episode: 21, name: "The Omega Directive" },
    { show: "Star Trek: Voyager", season: 4, episode: 22, name: "Unforgettable" },
    { show: "Star Trek: Voyager", season: 4, episode: 23, name: "Living Witness" },
    { show: "Star Trek: Voyager", season: 4, episode: 24, name: "Demon" },
    { show: "Star Trek: Voyager", season: 4, episode: 25, name: "One" },
    { show: "Star Trek: Voyager", season: 4, episode: 26, name: "Hope and Fear" },
    { show: "Star Trek: Voyager", season: 5, episode: 1, name: "Night" },
    { show: "Star Trek: Voyager", season: 5, episode: 2, name: "Drone" },
    { show: "Star Trek: Voyager", season: 5, episode: 3, name: "Extreme Risk" },
    { show: "Star Trek: Voyager", season: 5, episode: 4, name: "In the Flesh" },
    { show: "Star Trek: Voyager", season: 5, episode: 5, name: "Once Upon a Time" },
    { show: "Star Trek: Voyager", season: 5, episode: 6, name: "Timeless" },
    { show: "Star Trek: Voyager", season: 5, episode: 7, name: "Infinite Regress" },
    { show: "Star Trek: Voyager", season: 5, episode: 8, name: "Nothing Human" },
    { show: "Star Trek: Voyager", season: 5, episode: 9, name: "Thirty Days" },
    { show: "Star Trek: Voyager", season: 5, episode: 10, name: "Counterpoint" },
    { show: "Star Trek: Voyager", season: 5, episode: 11, name: "Latent Image" },
    { show: "Star Trek: Voyager", season: 5, episode: 12, name: "Bride of Chaotica!" },
    { show: "Star Trek: Voyager", season: 5, episode: 13, name: "Gravity" },
    { show: "Star Trek: Voyager", season: 5, episode: 14, name: "Bliss" },
    { show: "Star Trek: Voyager", season: 5, episode: 15, name: "Dark Frontier, Part I" },
    { show: "Star Trek: Voyager", season: 5, episode: 16, name: "Dark Frontier, Part II" },
    { show: "Star Trek: Voyager", season: 5, episode: 17, name: "The Disease" },
    { show: "Star Trek: Voyager", season: 5, episode: 18, name: "Course: Oblivion" },
    { show: "Star Trek: Voyager", season: 5, episode: 19, name: "The Fight" },
    { show: "Star Trek: Voyager", season: 5, episode: 20, name: "Think Tank" },
    { show: "Star Trek: Voyager", season: 5, episode: 21, name: "Juggernaut" },
    { show: "Star Trek: Voyager", season: 5, episode: 22, name: "Someone to Watch Over Me" },
    { show: "Star Trek: Voyager", season: 5, episode: 23, name: "11:59" },
    { show: "Star Trek: Voyager", season: 5, episode: 24, name: "Relativity" },
    { show: "Star Trek: Voyager", season: 5, episode: 25, name: "Warhead" },
    { show: "Star Trek: Voyager", season: 5, episode: 26, name: "Equinox, Part I" },
    { show: "Star Trek: Voyager", season: 6, episode: 1, name: 'Equinox, Part II' },
    { show: "Star Trek: Voyager", season: 6, episode: 2, name: 'Survival Instinct' },
    { show: "Star Trek: Voyager", season: 6, episode: 3, name: 'Barge of the Dead' },
    { show: "Star Trek: Voyager", season: 6, episode: 4, name: 'Tinker, Tenor, Doctor, Spy' },
    { show: "Star Trek: Voyager", season: 6, episode: 5, name: 'Alice' },
    { show: "Star Trek: Voyager", season: 6, episode: 6, name: 'Riddles' },
    { show: "Star Trek: Voyager", season: 6, episode: 7, name: 'Dragon\'s Teeth' },
    { show: "Star Trek: Voyager", season: 6, episode: 8, name: 'One Small Step' },
    { show: "Star Trek: Voyager", season: 6, episode: 9, name: 'The Voyager Conspiracy' },
    { show: "Star Trek: Voyager", season: 6, episode: 10, name: 'Pathfinder' },
    { show: "Star Trek: Voyager", season: 6, episode: 11, name: 'Fair Haven' },
    { show: "Star Trek: Voyager", season: 6, episode: 12, name: 'Blink of an Eye' },
    { show: "Star Trek: Voyager", season: 6, episode: 13, name: 'Virtuoso' },
    { show: "Star Trek: Voyager", season: 6, episode: 14, name: 'Memorial' },
    { show: "Star Trek: Voyager", season: 6, episode: 15, name: 'Tsunkatse' },
    { show: "Star Trek: Voyager", season: 6, episode: 16, name: 'Collective' },
    { show: "Star Trek: Voyager", season: 6, episode: 17, name: 'Spirit Folk' },
    { show: "Star Trek: Voyager", season: 6, episode: 18, name: 'Ashes to Ashes' },
    { show: "Star Trek: Voyager", season: 6, episode: 19, name: 'Child\'s Play' },
    { show: "Star Trek: Voyager", season: 6, episode: 20, name: 'Good Shepherd' },
    { show: "Star Trek: Voyager", season: 6, episode: 21, name: 'Live Fast and Prosper' },
    { show: "Star Trek: Voyager", season: 6, episode: 22, name: 'Muse' },
    { show: "Star Trek: Voyager", season: 6, episode: 23, name: 'Fury' },
    { show: "Star Trek: Voyager", season: 6, episode: 24, name: 'Life Line' },
    { show: "Star Trek: Voyager", season: 6, episode: 25, name: 'The Haunting of Deck Twelve' },
    { show: "Star Trek: Voyager", season: 6, episode: 26, name: 'Unimatrix Zero, Part I' },
    { show: "Star Trek: Voyager", season: 7, episode: 1, name: "Unimatrix Zero, Part II" },
    { show: "Star Trek: Voyager", season: 7, episode: 2, name: "Imperfection" },
    { show: "Star Trek: Voyager", season: 7, episode: 3, name: "Drive" },
    { show: "Star Trek: Voyager", season: 7, episode: 4, name: "Repression" },
    { show: "Star Trek: Voyager", season: 7, episode: 5, name: "Critical Care" },
    { show: "Star Trek: Voyager", season: 7, episode: 6, name: "Inside Man" },
    { show: "Star Trek: Voyager", season: 7, episode: 7, name: "Body and Soul" },
    { show: "Star Trek: Voyager", season: 7, episode: 8, name: "Nightingale" },
    { show: "Star Trek: Voyager", season: 7, episode: 9, name: "Flesh and Blood, Part I" },
    { show: "Star Trek: Voyager", season: 7, episode: 10, name: "Flesh and Blood, Part II" },
    { show: "Star Trek: Voyager", season: 7, episode: 11, name: "Shattered" },
    { show: "Star Trek: Voyager", season: 7, episode: 12, name: "Lineage" },
    { show: "Star Trek: Voyager", season: 7, episode: 13, name: "Repentance" },
    { show: "Star Trek: Voyager", season: 7, episode: 14, name: "Prophecy" },
    { show: "Star Trek: Voyager", season: 7, episode: 15, name: "The Void" },
    { show: "Star Trek: Voyager", season: 7, episode: 16, name: "Workforce, Part I" },
    { show: "Star Trek: Voyager", season: 7, episode: 17, name: "Workforce, Part II" },
    { show: "Star Trek: Voyager", season: 7, episode: 18, name: "Human Error" },
    { show: "Star Trek: Voyager", season: 7, episode: 19, name: "Q2" },
    { show: "Star Trek: Voyager", season: 7, episode: 20, name: "Author, Author" },
    { show: "Star Trek: Voyager", season: 7, episode: 21, name: "Friendship One" },
    { show: "Star Trek: Voyager", season: 7, episode: 22, name: "Natural Law" },
    { show: "Star Trek: Voyager", season: 7, episode: 23, name: "Homestead" },
    { show: "Star Trek: Voyager", season: 7, episode: 24, name: "Renaissance Man" },
    { show: "Star Trek: Voyager", season: 7, episode: 25, name: "Endgame, Part I" },
    { show: "Star Trek: Voyager", season: 7, episode: 26, name: "Endgame, Part II" },
];
const snwEpisodes = [
    { show: 'snw', season: 1, episode: 1, name: 'Strange New Worlds' },
    { show: 'snw', season: 1, episode: 2, name: 'Children of the Comet' },
    { show: 'snw', season: 1, episode: 3, name: 'Ghosts of Illyria' },
    { show: 'snw', season: 1, episode: 4, name: 'Memento Mori' },
    { show: 'snw', season: 1, episode: 5, name: 'Spock Amok' },
    { show: 'snw', season: 1, episode: 6, name: 'Lift Us Where Suffering Cannot Reach' },
    { show: 'snw', season: 1, episode: 7, name: 'The Elysian Kingdom' },
    { show: 'snw', season: 1, episode: 8, name: 'What Are Little Girls Made Of?' },
    { show: 'snw', season: 1, episode: 9, name: 'All Those Who Wander' },
    { show: 'snw', season: 1, episode: 10, name: 'A Quality of Mercy' }
];