const entEpisodes = [
    {show:"Star Trek: Enterprise", season: 1, episode: 1, name: "Broken Bow, Part I" },
    {show:"Star Trek: Enterprise", season: 1, episode: 2, name: "Broken Bow, Part II" },
    {show:"Star Trek: Enterprise", season: 1, episode: 3, name: "Fight or Flight" },
    {show:"Star Trek: Enterprise", season: 1, episode: 4, name: "Strange New World" },
    {show:"Star Trek: Enterprise", season: 1, episode: 5, name: "Unexpected" },
    {show:"Star Trek: Enterprise", season: 1, episode: 6, name: "Terra Nova" },
    {show:"Star Trek: Enterprise", season: 1, episode: 7, name: "The Andorian Incident" },
    {show:"Star Trek: Enterprise", season: 1, episode: 8, name: "Breaking the Ice" },
    {show:"Star Trek: Enterprise", season: 1, episode: 9, name: "Civilization" },
    {show:"Star Trek: Enterprise", season: 1, episode: 10, name: "Fortunate Son" },
    {show:"Star Trek: Enterprise", season: 1, episode: 11, name: "Cold Front" },
    {show:"Star Trek: Enterprise", season: 1, episode: 12, name: "Silent Enemy" },
    {show:"Star Trek: Enterprise", season: 1, episode: 13, name: "Dear Doctor" },
    {show:"Star Trek: Enterprise", season: 1, episode: 14, name: "Sleeping Dogs" },
    {show:"Star Trek: Enterprise", season: 1, episode: 15, name: "Shadows of P'Jem" },
    {show:"Star Trek: Enterprise", season: 1, episode: 16, name: "Shuttlepod One" },
    {show:"Star Trek: Enterprise", season: 1, episode: 17, name: "Fusion" },
    {show:"Star Trek: Enterprise", season: 1, episode: 18, name: "Rogue Planet" },
    {show:"Star Trek: Enterprise", season: 1, episode: 19, name: "Acquisition" },
    {show:"Star Trek: Enterprise", season: 1, episode: 20, name: "Oasis" },
    {show:"Star Trek: Enterprise", season: 1, episode: 21, name: "Detained" },
    {show:"Star Trek: Enterprise", season: 1, episode: 22, name: "Vox Sola" },
    {show:"Star Trek: Enterprise", season: 1, episode: 23, name: "Fallen Hero" },
    {show:"Star Trek: Enterprise", season: 1, episode: 24, name: "Desert Crossing" },
    {show:"Star Trek: Enterprise", season: 1, episode: 25, name: "Two Days and Two Nights" },
    {show:"Star Trek: Enterprise", season: 1, episode: 26, name: "Shockwave, Part I" },
    {show:"Star Trek: Enterprise", season: 2, episode: 1, name: "Shockwave, Part II" },
    {show:"Star Trek: Enterprise", season: 2, episode: 2, name: "Carbon Creek" },
    {show:"Star Trek: Enterprise", season: 2, episode: 3, name: "Minefield" },
    {show:"Star Trek: Enterprise", season: 2, episode: 4, name: "Dead Stop" },
    {show:"Star Trek: Enterprise", season: 2, episode: 5, name: "A Night in Sickbay" },
    {show:"Star Trek: Enterprise", season: 2, episode: 6, name: "Marauders" },
    {show:"Star Trek: Enterprise", season: 2, episode: 7, name: "The Seventh" },
    {show:"Star Trek: Enterprise", season: 2, episode: 8, name: "The Communicator" },
    {show:"Star Trek: Enterprise", season: 2, episode: 9, name: "Singularity" },
    {show:"Star Trek: Enterprise", season: 2, episode: 10, name: "Vanishing Point" },
    {show:"Star Trek: Enterprise", season: 2, episode: 11, name: "Precious Cargo" },
    {show:"Star Trek: Enterprise", season: 2, episode: 12, name: "The Catwalk" },
    {show:"Star Trek: Enterprise", season: 2, episode: 13, name: "Dawn" },
    {show:"Star Trek: Enterprise", season: 2, episode: 14, name: "Stigma" },
    {show:"Star Trek: Enterprise", season: 2, episode: 15, name: "Cease Fire" },
    {show:"Star Trek: Enterprise", season: 2, episode: 16, name: "Future Tense" },
    {show:"Star Trek: Enterprise", season: 2, episode: 17, name: "Canamar" },
    {show:"Star Trek: Enterprise", season: 2, episode: 18, name: "The Crossing" },
    {show:"Star Trek: Enterprise", season: 2, episode: 19, name: "Judgment" },
    {show:"Star Trek: Enterprise", season: 2, episode: 20, name: "Horizon" },
    {show:"Star Trek: Enterprise", season: 2, episode: 21, name: "The Breach" },
    {show:"Star Trek: Enterprise", season: 2, episode: 22, name: "Cogenitor" },
    {show:"Star Trek: Enterprise", season: 2, episode: 23, name: "Regeneration" },
    {show:"Star Trek: Enterprise", season: 2, episode: 24, name: "First Flight" },
    {show:"Star Trek: Enterprise", season: 2, episode: 25, name: "Bounty" },
    {show:"Star Trek: Enterprise", season: 2, episode: 26, name: "The Expanse" },
    {show:"Star Trek: Enterprise", season: 3, episode: 1, name: "The Xindi" },
    {show:"Star Trek: Enterprise", season: 3, episode: 2, name: "Anomaly" },
    {show:"Star Trek: Enterprise", season: 3, episode: 3, name: "Extinction" },
    {show:"Star Trek: Enterprise", season: 3, episode: 4, name: "Rajiin" },
    {show:"Star Trek: Enterprise", season: 3, episode: 5, name: "Impulse" },
    {show:"Star Trek: Enterprise", season: 3, episode: 6, name: "Exile" },
    {show:"Star Trek: Enterprise", season: 3, episode: 7, name: "The Shipment" },
    {show:"Star Trek: Enterprise", season: 3, episode: 8, name: "Twilight" },
    {show:"Star Trek: Enterprise", season: 3, episode: 9, name: "North Star" },
    {show:"Star Trek: Enterprise", season: 3, episode: 10, name: "Similitude" },
    {show:"Star Trek: Enterprise", season: 3, episode: 11, name: "Carpenter Street" },
    {show:"Star Trek: Enterprise", season: 3, episode: 12, name: "Chosen Realm" },
    {show:"Star Trek: Enterprise", season: 3, episode: 13, name: "Proving Ground" },
    {show:"Star Trek: Enterprise", season: 3, episode: 14, name: "Stratagem" },
    {show:"Star Trek: Enterprise", season: 3, episode: 15, name: "Harbinger" },
    {show:"Star Trek: Enterprise", season: 3, episode: 16, name: "Doctor's Orders" },
    {show:"Star Trek: Enterprise", season: 3, episode: 17, name: "Hatchery" },
    {show:"Star Trek: Enterprise", season: 3, episode: 18, name: "Azati Prime" },
    {show:"Star Trek: Enterprise", season: 3, episode: 19, name: "Damage" },
    {show:"Star Trek: Enterprise", season: 3, episode: 20, name: "The Forgotten" },
    {show:"Star Trek: Enterprise", season: 3, episode: 21, name: "E²" },
    {show:"Star Trek: Enterprise", season: 3, episode: 22, name: "The Council" },
    {show:"Star Trek: Enterprise", season: 3, episode: 23, name: "Countdown" },
    {show:"Star Trek: Enterprise", season: 3, episode: 24, name: "Zero Hour" },
    {show:"Star Trek: Enterprise", season: 4, episode: 1, name: "Storm Front, Part I" },
    {show:"Star Trek: Enterprise", season: 4, episode: 2, name: "Storm Front, Part II" },
    {show:"Star Trek: Enterprise", season: 4, episode: 3, name: "Home" },
    {show:"Star Trek: Enterprise", season: 4, episode: 4, name: "Borderland" },
    {show:"Star Trek: Enterprise", season: 4, episode: 5, name: "Cold Station 12" },
    {show:"Star Trek: Enterprise", season: 4, episode: 6, name: "The Augments" },
    {show:"Star Trek: Enterprise", season: 4, episode: 7, name: "The Forge" },
    {show:"Star Trek: Enterprise", season: 4, episode: 8, name: "Awakening" },
    {show:"Star Trek: Enterprise", season: 4, episode: 9, name: "Kir'Shara" },
    {show:"Star Trek: Enterprise", season: 4, episode: 10, name: "Daedalus" },
    {show:"Star Trek: Enterprise", season: 4, episode: 11, name: "Observer Effect" },
    {show:"Star Trek: Enterprise", season: 4, episode: 12, name: "Babel One" },
    {show:"Star Trek: Enterprise", season: 4, episode: 13, name: "United" },
    {show:"Star Trek: Enterprise", season: 4, episode: 14, name: "The Aenar" },
    {show:"Star Trek: Enterprise", season: 4, episode: 15, name: "Affliction" },
    {show:"Star Trek: Enterprise", season: 4, episode: 16, name: "Divergence" },
    {show:"Star Trek: Enterprise", season: 4, episode: 17, name: "Bound" },
    {show:"Star Trek: Enterprise", season: 4, episode: 18, name: "In a Mirror, Darkly, Part I" },
    {show:"Star Trek: Enterprise", season: 4, episode: 19, name: "In a Mirror, Darkly, Part II" },
    {show:"Star Trek: Enterprise", season: 4, episode: 20, name: "Demons" },
    {show:"Star Trek: Enterprise", season: 4, episode: 21, name: "Terra Prime" },
    {show:"Star Trek: Enterprise", season: 4, episode: 22, name: "These Are the Voyages..." }
    ];

const tosEpisodes = [
    {show: "Star Trek: The Original Series", season: 1, episode: 1, name: "The Man Trap" },
    {show: "Star Trek: The Original Series", season: 1, episode: 2, name: "Charlie X" },
    {show: "Star Trek: The Original Series", season: 1, episode: 3, name: "Where No Man Has Gone Before" },
    {show: "Star Trek: The Original Series", season: 1, episode: 4, name: "The Naked Time" },
    {show: "Star Trek: The Original Series", season: 1, episode: 5, name: "The Enemy Within" },
    {show: "Star Trek: The Original Series", season: 1, episode: 6, name: "Mudd's Women" },
    {show: "Star Trek: The Original Series", season: 1, episode: 7, name: "What Are Little Girls Made Of?" },
    {show: "Star Trek: The Original Series", season: 1, episode: 8, name: "Miri" },
    {show: "Star Trek: The Original Series", season: 1, episode: 9, name: "Dagger of the Mind" },
    {show: "Star Trek: The Original Series", season: 1, episode: 10, name: "The Corbomite Maneuver" },
    {show: "Star Trek: The Original Series", season: 1, episode: 11, name: "The Menagerie, Part I" },
    {show: "Star Trek: The Original Series", season: 1, episode: 12, name: "The Menagerie, Part II" },
    {show: "Star Trek: The Original Series", season: 1, episode: 13, name: "The Conscience of the King" },
    {show: "Star Trek: The Original Series", season: 1, episode: 14, name: "Balance of Terror" },
    {show: "Star Trek: The Original Series", season: 1, episode: 15, name: "Shore Leave" },
    {show: "Star Trek: The Original Series", season: 1, episode: 16, name: "The Galileo Seven" },
    {show: "Star Trek: The Original Series", season: 1, episode: 17, name: "The Squire of Gothos" },
    {show: "Star Trek: The Original Series", season: 1, episode: 18, name: "Arena" },
    {show: "Star Trek: The Original Series", season: 1, episode: 19, name: "Tomorrow Is Yesterday" },
    {show: "Star Trek: The Original Series", season: 1, episode: 20, name: "Court Martial" },
    {show: "Star Trek: The Original Series", season: 1, episode: 21, name: "The Return of the Archons" },
    {show: "Star Trek: The Original Series", season: 1, episode: 22, name: "Space Seed" },
    {show: "Star Trek: The Original Series", season: 1, episode: 23, name: "A Taste of Armageddon" },
    {show: "Star Trek: The Original Series", season: 1, episode: 24, name: "This Side of Paradise" },
    {show: "Star Trek: The Original Series", season: 1, episode: 25, name: "The Devil in the Dark" },
    {show: "Star Trek: The Original Series", season: 1, episode: 26, name: "Errand of Mercy" },
    {show: "Star Trek: The Original Series", season: 2, episode: 1, name: "Amok Time" },
    {show: "Star Trek: The Original Series", season: 2, episode: 2, name: "Who Mourns for Adonais?" },
    {show: "Star Trek: The Original Series", season: 2, episode: 3, name: "The Changeling" },
    {show: "Star Trek: The Original Series", season: 2, episode: 4, name: "Mirror, Mirror" },
    {show: "Star Trek: The Original Series", season: 2, episode: 5, name: "The Apple" },
    {show: "Star Trek: The Original Series", season: 2, episode: 6, name: "The Doomsday Machine" },
    {show: "Star Trek: The Original Series", season: 2, episode: 7, name: "Catspaw" },
    {show: "Star Trek: The Original Series", season: 2, episode: 8, name: "I, Mudd" },
    {show: "Star Trek: The Original Series", season: 2, episode: 9, name: "Metamorphosis" },
    {show: "Star Trek: The Original Series", season: 2, episode: 10, name: "Journey to Babel" },
    {show: "Star Trek: The Original Series", season: 2, episode: 11, name: "Friday's Child" },
    {show: "Star Trek: The Original Series", season: 2, episode: 12, name: "The Deadly Years" },
    {show: "Star Trek: The Original Series", season: 2, episode: 13, name: "Obsession" },
    {show: "Star Trek: The Original Series", season: 2, episode: 14, name: "Wolf in the Fold" },
    {show: "Star Trek: The Original Series", season: 2, episode: 15, name: "The Trouble with Tribbles" },
    {show: "Star Trek: The Original Series", season: 2, episode: 16, name: "The Gamesters of Triskelion" },
    {show: "Star Trek: The Original Series", season: 2, episode: 17, name: "A Piece of the Action" },
    {show: "Star Trek: The Original Series", season: 2, episode: 18, name: "The Immunity Syndrome" },
    {show: "Star Trek: The Original Series", season: 2, episode: 19, name: "A Private Little War" },
    {show: "Star Trek: The Original Series", season: 2, episode: 20, name: "Return to Tomorrow" },
    {show: "Star Trek: The Original Series", season: 2, episode: 21, name: "Patterns of Force" },
    {show: "Star Trek: The Original Series", season: 2, episode: 22, name: "By Any Other Name" },
    {show: "Star Trek: The Original Series", season: 2, episode: 23, name: "The Omega Glory" },
    {show: "Star Trek: The Original Series", season: 2, episode: 24, name: "The Ultimate Computer" },
    {show: "Star Trek: The Original Series", season: 2, episode: 25, name: "Bread and Circuses" },
    {show: "Star Trek: The Original Series", season: 2, episode: 26, name: "Assignment: Earth" },
    {show: "Star Trek: The Original Series", season: 3, episode: 1, name: "Spock's Brain" },
    {show: "Star Trek: The Original Series", season: 3, episode: 2, name: "The Enterprise Incident" },
    {show: "Star Trek: The Original Series", season: 3, episode: 4, name: "And the Children Shall Lead" },
    {show: "Star Trek: The Original Series", season: 3, episode: 5, name: "Is There in Truth No Beauty?" },
    {show: "Star Trek: The Original Series", season: 3, episode: 6, name: "Spectre of the Gun" },
    {show: "Star Trek: The Original Series", season: 3, episode: 7, name: "Day of the Dove" },
    {show: "Star Trek: The Original Series", season: 3, episode: 9, name: "The Tholian Web" },
    {show: "Star Trek: The Original Series", season: 3, episode: 10, name: "Plato's Stepchildren" },
    {show: "Star Trek: The Original Series", season: 3, episode: 11, name: "Wink of an Eye" },
    {show: "Star Trek: The Original Series", season: 3, episode: 12, name: "The Empath" },
    {show: "Star Trek: The Original Series", season: 3, episode: 13, name: "Elaan of Troyius" },
    {show: "Star Trek: The Original Series", season: 3, episode: 14, name: "Whom Gods Destroy" },
    {show: "Star Trek: The Original Series", season: 3, episode: 15, name: "Let That Be Your Last Battlefield" },
    {show: "Star Trek: The Original Series", season: 3, episode: 16, name: "The Mark of Gideon" },
    {show: "Star Trek: The Original Series", season: 3, episode: 17, name: "That Which Survives" },
    {show: "Star Trek: The Original Series", season: 3, episode: 18, name: "The Lights of Zetar" },
    {show: "Star Trek: The Original Series", season: 3, episode: 19, name: "Requiem for Methuselah" },
    {show: "Star Trek: The Original Series", season: 3, episode: 20, name: "The Way to Eden" },
    {show: "Star Trek: The Original Series", season: 3, episode: 21, name: "The Cloud Minders" },
    {show: "Star Trek: The Original Series", season: 3, episode: 22, name: "The Savage Curtain" },
    {show: "Star Trek: The Original Series", season: 3, episode: 23, name: "All Our Yesterdays" },
    {show: "Star Trek: The Original Series", season: 3, episode: 24, name: "Turnabout Intruder" }
    ];
const tngEpisodes = [
    { show: "TNG", season: 1, episode: 1, name: "Encounter at Farpoint, Part I" },
    { show: "TNG", season: 1, episode: 2, name: "Encounter at Farpoint, Part II" },
    { show: "TNG", season: 1, episode: 3, name: "The Naked Now" },
    { show: "TNG", season: 1, episode: 4, name: "Code of Honor" },
    { show: "TNG", season: 1, episode: 5, name: "The Last Outpost" },
    { show: "TNG", season: 1, episode: 6, name: "Where No One Has Gone Before" },
    { show: "TNG", season: 1, episode: 7, name: "Lonely Among Us" },
    { show: "TNG", season: 1, episode: 8, name: "Justice" },
    { show: "TNG", season: 1, episode: 9, name: "The Battle" },
    { show: "TNG", season: 1, episode: 10, name: "Hide and Q" },
    { show: "TNG", season: 1, episode: 11, name: "Haven" },
    { show: "TNG", season: 1, episode: 12, name: "The Big Goodbye" },
    { show: "TNG", season: 1, episode: 13, name: "Datalore" },
    { show: "TNG", season: 1, episode: 14, name: "Angel One" },
    { show: "TNG", season: 1, episode: 15, name: "11001001" },
    { show: "TNG", season: 1, episode: 16, name: "Too Short a Season" },
    { show: "TNG", season: 1, episode: 17, name: "When the Bough Breaks" },
    { show: "TNG", season: 1, episode: 18, name: "Home Soil" },
    { show: "TNG", season: 1, episode: 19, name: "Coming of Age" },
    { show: "TNG", season: 1, episode: 20, name: "Heart of Glory" },
    { show: "TNG", season: 1, episode: 21, name: "The Arsenal of Freedom" },
    { show: "TNG", season: 1, episode: 22, name: "Symbiosis" },
    { show: "TNG", season: 1, episode: 23, name: "Skin of Evil" },
    { show: "TNG", season: 1, episode: 24, name: "We'll Always Have Paris" },
    { show: "TNG", season: 1, episode: 25, name: "Conspiracy" },
    { show: "TNG", season: 1, episode: 26, name: "The Neutral Zone" },
    { show: "TNG", season: 2, episode: 1, name: "The Child" },
    { show: "TNG", season: 2, episode: 2, name: "Where Silence Has Lease" },
    { show: "TNG", season: 2, episode: 3, name: "Elementary, Dear Data" },
    { show: "TNG", season: 2, episode: 4, name: "The Outrageous Okona" },
    { show: "TNG", season: 2, episode: 5, name: "Loud as a Whisper" },
    { show: "TNG", season: 2, episode: 6, name: "The Schizoid Man" },
    { show: "TNG", season: 2, episode: 7, name: "Unnatural Selection" },
    { show: "TNG", season: 2, episode: 8, name: "A Matter of Honor" },
    { show: "TNG", season: 2, episode: 9, name: "The Measure of a Man" },
    { show: "TNG", season: 2, episode: 10, name: "The Dauphin" },
    { show: "TNG", season: 2, episode: 11, name: "Contagion" },
    { show: "TNG", season: 2, episode: 12, name: "The Royale" },
    { show: "TNG", season: 2, episode: 13, name: "Time Squared" },
    { show: "TNG", season: 2, episode: 14, name: "The Icarus Factor" },
    { show: "TNG", season: 2, episode: 15, name: "Pen Pals" },
    { show: "TNG", season: 2, episode: 16, name: "Q Who" },
    { show: "TNG", season: 2, episode: 17, name: "Samaritan Snare" },
    { show: "TNG", season: 2, episode: 18, name: "Up the Long Ladder" },
    { show: "TNG", season: 2, episode: 19, name: "Manhunt" },
    { show: "TNG", season: 2, episode: 20, name: "The Emissary" },
    { show: "TNG", season: 2, episode: 21, name: "Peak Performance" },
    { show: "TNG", season: 2, episode: 22, name: "Shades of Gray" },
    { show: "TNG", season: 3, episode: 1, name: "Evolution" },
    { show: "TNG", season: 3, episode: 2, name: "The Ensigns of Command" },
    { show: "TNG", season: 3, episode: 3, name: "The Survivors" },
    { show: "TNG", season: 3, episode: 4, name: "Who Watches the Watchers" },
    { show: "TNG", season: 3, episode: 5, name: "The Bonding" },
    { show: "TNG", season: 3, episode: 6, name: "Booby Trap" },
    { show: "TNG", season: 3, episode: 7, name: "The Enemy" },
    { show: "TNG", season: 3, episode: 8, name: "The Price" },
    { show: "TNG", season: 3, episode: 9, name: "The Vengeance Factor" },
    { show: "TNG", season: 3, episode: 10, name: "The Defector" },
    { show: "TNG", season: 3, episode: 11, name: "The Hunted" },
    { show: "TNG", season: 3, episode: 12, name: "The High Ground" },
    { show: "TNG", season: 3, episode: 13, name: "Deja Q" },
    { show: "TNG", season: 3, episode: 14, name: "A Matter of Perspective" },
    { show: "TNG", season: 3, episode: 15, name: "Yesterday's Enterprise" },
    { show: "TNG", season: 3, episode: 16, name: "The Offspring" },
    { show: "TNG", season: 3, episode: 17, name: "Sins of the Father" },
    { show: "TNG", season: 3, episode: 18, name: "Allegiance" },
    { show: "TNG", season: 3, episode: 19, name: "Captain's Holiday" },
    { show: "TNG", season: 3, episode: 20, name: "Tin Man" },
    { show: "TNG", season: 3, episode: 21, name: "Hollow Pursuits" },
    { show: "TNG", season: 3, episode: 22, name: "The Most Toys" },
    { show: "TNG", season: 3, episode: 23, name: "Sarek" },
    { show: "TNG", season: 3, episode: 24, name: "Ménage à Troi" },
    { show: "TNG", season: 3, episode: 25, name: "Transfigurations" },
    { show: "TNG", season: 3, episode: 26, name: "The Best of Both Worlds: Part 1" },
    { show: "TNG", season: 4, episode: 1, name: "The Best of Both Worlds: Part 2" },
    { show: "TNG", season: 4, episode: 2, name: "Family" },
    { show: "TNG", season: 4, episode: 3, name: "Brothers" },
    { show: "TNG", season: 4, episode: 4, name: "Suddenly Human" },
    { show: "TNG", season: 4, episode: 5, name: "Remember Me" },
    { show: "TNG", season: 4, episode: 6, name: "Legacy" },
    { show: "TNG", season: 4, episode: 7, name: "Reunion" },
    { show: "TNG", season: 4, episode: 8, name: "Future Imperfect" },
    { show: "TNG", season: 4, episode: 9, name: "Final Mission" },
    { show: "TNG", season: 4, episode: 10, name: "The Loss" },
    { show: "TNG", season: 4, episode: 11, name: "Data's Day" },
    { show: "TNG", season: 4, episode: 12, name: "The Wounded" },
    { show: "TNG", season: 4, episode: 13, name: "Devil's Due" },
    { show: "TNG", season: 4, episode: 14, name: "Clues" },
    { show: "TNG", season: 4, episode: 15, name: "First Contact" },
    { show: "TNG", season: 4, episode: 16, name: "Galaxy's Child" },
    { show: "TNG", season: 4, episode: 17, name: "Night Terrors" },
    { show: "TNG", season: 4, episode: 18, name: "Identity Crisis" },
    { show: "TNG", season: 4, episode: 19, name: "The Nth Degree" },
    { show: "TNG", season: 4, episode: 20, name: "Qpid" },
    { show: "TNG", season: 4, episode: 21, name: "The Drumhead" },
    { show: "TNG", season: 4, episode: 22, name: "Half a Life" },
    { show: "TNG", season: 4, episode: 23, name: "The Host" },
    { show: "TNG", season: 4, episode: 24, name: "The Mind's Eye" },
    { show: "TNG", season: 4, episode: 25, name: "In Theory" },
    { show: "TNG", season: 4, episode: 26, name: "Redemption: Part 1" },
    { show: "TNG", season: 5, episode: 1, name: "Redemption: Part 2" },
    { show: "TNG", season: 5, episode: 2, name: "Darmok" },
    { show: "TNG", season: 5, episode: 3, name: "Ensign Ro" },
    { show: "TNG", season: 5, episode: 4, name: "Silicon Avatar" },
    { show: "TNG", season: 5, episode: 5, name: "Disaster" },
    { show: "TNG", season: 5, episode: 6, name: "The Game" },
    { show: "TNG", season: 5, episode: 7, name: "Unification: Part 1" },
    { show: "TNG", season: 5, episode: 8, name: "Unification: Part 2" },
    { show: "TNG", season: 5, episode: 9, name: "A Matter of Time" },
    { show: "TNG", season: 5, episode: 10, name: "New Ground" },
    { show: "TNG", season: 5, episode: 11, name: "Hero Worship" },
    { show: "TNG", season: 5, episode: 12, name: "Violations" },
    { show: "TNG", season: 5, episode: 13, name: "The Masterpiece Society" },
    { show: "TNG", season: 5, episode: 14, name: "Conundrum" },
    { show: "TNG", season: 5, episode: 15, name: "Power Play" },
    { show: "TNG", season: 5, episode: 16, name: "Ethics" },
{ show: "TNG", season: 5, episode: 17, name: "The Outcast" },
{ show: "TNG", season: 5, episode: 18, name: "Cause and Effect" },
{ show: "TNG", season: 5, episode: 19, name: "The First Duty" },
{ show: "TNG", season: 5, episode: 20, name: "Cost of Living" },
{ show: "TNG", season: 5, episode: 21, name: "The Perfect Mate" },
{ show: "TNG", season: 5, episode: 22, name: "Imaginary Friend" },
{ show: "TNG", season: 5, episode: 23, name: "I Borg" },
{ show: "TNG", season: 5, episode: 24, name: "The Next Phase" },
{ show: "TNG", season: 5, episode: 25, name: "The Inner Light" },
{ show: "TNG", season: 5, episode: 26, name: "Time's Arrow: Part 1" },
{ show: "TNG", season: 6, episode: 1, name: "Time's Arrow: Part 2" },
{ show: "TNG", season: 6, episode: 2, name: "Realm of Fear" },
{ show: "TNG", season: 6, episode: 3, name: "Man of the People" },
{ show: "TNG", season: 6, episode: 4, name: "Relics" },
{ show: "TNG", season: 6, episode: 5, name: "Schisms" },
{ show: "TNG", season: 6, episode: 6, name: "True Q" },
{ show: "TNG", season: 6, episode: 7, name: "Rascals" },
{ show: "TNG", season: 6, episode: 8, name: "A Fistful of Datas" },
{ show: "TNG", season: 6, episode: 9, name: "The Quality of Life" },
{ show: "TNG", season: 6, episode: 10, name: "Chain of Command: Part 1" },
{ show: "TNG", season: 6, episode: 11, name: "Chain of Command: Part 2" },
{ show: "TNG", season: 6, episode: 12, name: "Ship in a Bottle" },
{ show: "TNG", season: 6, episode: 13, name: "Aquiel" },
{ show: "TNG", season: 6, episode: 14, name: "Face of the Enemy" },
{ show: "TNG", season: 6, episode: 15, name: "Tapestry" },
{ show: "TNG", season: 6, episode: 16, name: "Birthright: Part 1" },
{ show: "TNG", season: 6, episode: 17, name: "Birthright: Part 2" },
{ show: "TNG", season: 6, episode: 18, name: "Starship Mine" },
{ show: "TNG", season: 6, episode: 19, name: "Lessons" },
{ show: "TNG", season: 6, episode: 20, name: "The Chase" },
{ show: "TNG", season: 6, episode: 21, name: "Frame of Mind" },
{ show: "TNG", season: 6, episode: 22, name: "Suspicions" },
{ show: "TNG", season: 6, episode: 23, name: "Rightful Heir" },
{ show: "TNG", season: 6, episode: 24, name: "Second Chances" },
{ show: "TNG", season: 6, episode: 25, name: "Timescape" },
{ show: "TNG", season: 6, episode: 26, name: "Descent: Part 1" },
{ show: "TNG", season: 7, episode: 1, name: "Descent: Part 2" },
{ show: "TNG", season: 7, episode: 2, name: "Liaisons" },
{ show: "TNG", season: 7, episode: 3, name: "Interface" },
{ show: "TNG", season: 7, episode: 4, name: "Gambit: Part 1" },
{ show: "TNG", season: 7, episode: 5, name: "Gambit: Part 2" },
{ show: "TNG", season: 7, episode: 6, name: "Phantasms" },
{ show: "TNG", season: 7, episode: 7, name: "Dark Page" },
{ show: "TNG", season: 7, episode: 8, name: "Attached" },
{ show: "TNG", season: 7, episode: 9, name: "Force of Nature" },
{ show: "TNG", season: 7, episode: 10, name: "Inheritance" },
{ show: "TNG", season: 7, episode: 11, name: "Parallels" },
{ show: "TNG", season: 7, episode: 12, name: "The Pegasus" },
{ show: "TNG", season: 7, episode: 13, name: "Homeward" },
{ show: "TNG", season: 7, episode: 14, name: "Sub Rosa" },
{ show: "TNG", season: 7, episode: 15, name: "Lower Decks" },
{ show: "TNG", season: 7, episode: 16, name: "Thine Own Self" },
{ show: "TNG", season: 7, episode: 17, name: "Masks" },
{ show: "TNG", season: 7, episode: 18, name: "Eye of the Beholder" },
{ show: "TNG", season: 7, episode: 19, name: "Genesis" },
{ show: "TNG", season: 7, episode: 20, name: "Journey's End" },
{ show: "TNG", season: 7, episode: 21, name: "Firstborn" },
{ show: "TNG", season: 7, episode: 22, name: "Bloodlines" },
{ show: "TNG", season: 7, episode: 23, name: "Emergence" },
{ show: "TNG", season: 7, episode: 24, name: "Preemptive Strike" },
{ show: "TNG", season: 7, episode: 25, name: "All Good Things..." },
];